# **Cleaning New York County Health Rankings**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
pd.set_option('max_columns', 400)
pd.set_option('max_rows', 10)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 2019_health_r.xlsx to 2019_health_r.xlsx
Saving 2020_health_r.xlsx to 2020_health_r.xlsx
Saving 2021_health_r.xlsx to 2021_health_r.xlsx

##Cleaning 2019 data
Resulting dataframe **rank2019**

### 1st sheet: Outcomes & Factors Rankings

In [ ]:
df1=pd.read_excel("2019_health_r.xlsx",sheet_name='Outcomes & Factors Rankings')
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Health Outcomes,Unnamed: 4,Health Factors,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,36087,New York,Rockland,-1.61792,1,-0.589033,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,36059,New York,Nassau,-1.31488,2,-1.10687,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36119,New York,Westchester,-1.31184,3,-0.746898,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,36091,New York,Saratoga,-1.2757,4,-0.819766,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36061,New York,New York,-1.18877,5,-0.380348,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36009,New York,Cattaraugus,1.26987,60,0.651674,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,36105,New York,Sullivan,1.36201,61,0.383453,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,36005,New York,Bronx,1.55743,62,1.37171,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,FIPS,State,County,Z-Score,Rank,Z-Score,Rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,36000,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Deleting colums
df1c=df1.drop(columns=df1.iloc[:,7:19])
#Deleting rows
df1c=df1c.drop([62,63])

#Renaming columns
new_col1={'Unnamed: 0': 'fips',
         'Unnamed: 1': 'state',
         'Unnamed: 2': 'county_name',
         'Health Outcomes': 'health_outcomes_z',
         'Unnamed: 4': 'health_outcomes_r',
         'Health Factors': 'health_factors_z',
         'Unnamed: 6': 'health_factors_r'}
df1c=df1c.rename(columns=new_col1)
df1c

,fips,state,county_name,health_outcomes_z,health_outcomes_r,health_factors_z,health_factors_r
0,36087,New York,Rockland,-1.61792,1,-0.589033,6
1,36059,New York,Nassau,-1.31488,2,-1.10687,1
2,36119,New York,Westchester,-1.31184,3,-0.746898,4
3,36091,New York,Saratoga,-1.2757,4,-0.819766,2
4,36061,New York,New York,-1.18877,5,-0.380348,12
...,...,...,...,...,...,...,...
57,36063,New York,Niagara,1.14268,58,0.434817,52
58,36013,New York,Chautauqua,1.17547,59,0.501706,55
59,36009,New York,Cattaraugus,1.26987,60,0.651674,61
60,36105,New York,Sullivan,1.36201,61,0.383453,50
61,36005,New York,Bronx,1.55743,62,1.37171,62

### 2nd Sheet: Outcomes & Factors SubRankings

In [ ]:
df2=pd.read_excel("2019_health_r.xlsx",sheet_name='Outcomes & Factors SubRankings')
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Length of Life,Unnamed: 4,Quality of Life,Unnamed: 6,Health Behaviors,Unnamed: 8,Clinical Care,Unnamed: 10,Social & Economic Factors,Unnamed: 12,Physical Environment,Unnamed: 14
0,FIPS,State,County,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank
1,36000,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36001,New York,Albany,-0.342749,16,0.0243054,34,-0.138112,13,-0.151688,5,-0.30611,7,0.0153054,42
3,36003,New York,Allegany,0.118514,33,0.162494,42,0.198174,56,-0.0275808,29,0.16298,50,0.00212904,36
4,36005,New York,Bronx,0.135122,35,1.42231,62,0.0592182,39,0.365994,62,0.855121,62,0.0913738,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.114466,32,-0.0031966,29,0.0976657,43,0.0328879,42,-0.00800546,27,0.0329123,50
60,36117,New York,Wayne,0.364871,45,0.277918,51,0.1751,53,0.115236,53,-0.126899,17,-0.0353008,13
61,36119,New York,Westchester,-1.11221,2,-0.199624,19,-0.443775,2,-0.0702673,17,-0.30794,6,0.075084,60
62,36121,New York,Wyoming,-0.0615371,24,-0.203381,17,0.155006,49,0.0226992,39,-0.0878606,20,0.00802409,37
63,36123,New York,Yates,0.101666,31,-0.762204,2,-0.04519,22,0.124247,56,0.0241893,32,-0.0151356,25

In [ ]:
#Remove columns
to_remove=df2.iloc[:,np.r_[1:3,7:15]]
df2c=df2.drop(columns=to_remove)

#Remove rows
df2c=df2c.drop([0,1])

#Rename columns
new_col2={'Unnamed: 0':'fips',
          'Length of Life':'lenght_life_z',
          'Unnamed: 4':'length_life_r',
          'Quality of Life':'quality_life_z',
          'Unnamed: 6':'quality_life_r'}
df2c=df2c.rename(columns=new_col2)
df2c

     fips lenght_life_z length_life_r quality_life_z quality_life_r
2   36001     -0.342749            16      0.0243054             34
3   36003      0.118514            33       0.162494             42
4   36005      0.135122            35        1.42231             62
5   36007      0.612147            57       0.299747             53
6   36009      0.506634            54       0.763238             61
..    ...           ...           ...            ...            ...
59  36115      0.114466            32     -0.0031966             29
60  36117      0.364871            45       0.277918             51
61  36119      -1.11221             2      -0.199624             19
62  36121    -0.0615371            24      -0.203381             17
63  36123      0.101666            31      -0.762204              2

[62 rows x 5 columns]

### 3rd Sheet: Ranked Measure Data

In [ ]:
df3=pd.read_excel("2019_health_r.xlsx",sheet_name='Ranked Measure Data')
df3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Premature death,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Poor or fair health,Unnamed: 11,Unnamed: 12,Unnamed: 13,Poor physical health days,Unnamed: 15,Unnamed: 16,Unnamed: 17,Poor mental health days,Unnamed: 19,Unnamed: 20,Unnamed: 21,Low birthweight,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Adult smoking,Unnamed: 31,Unnamed: 32,Unnamed: 33,Adult obesity,Unnamed: 35,Unnamed: 36,Unnamed: 37,Food environment index,Unnamed: 39,Physical inactivity,Unnamed: 41,Unnamed: 42,Unnamed: 43,Access to exercise opportunities,Unnamed: 45,Excessive drinking,Unnamed: 47,Unnamed: 48,Unnamed: 49,Alcohol-impaired driving deaths,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Sexually transmitted infections,Unnamed: 57,Unnamed: 58,Teen births,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Uninsured,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Primary care physicians,Unnamed: 72,Unnamed: 73,Unnamed: 74,Dentists,Unnamed: 76,Unnamed: 77,Unnamed: 78,Mental health providers,Unnamed: 80,Unnamed: 81,Unnamed: 82,Preventable hospital stays,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Mammography screening,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Flu vaccinations,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,High school graduation,Unnamed: 99,Unnamed: 100,Some college,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unemployment,Unnamed: 108,Unnamed: 109,Unnamed: 110,Children in poverty,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Income inequality,Unnamed: 119,Unnamed: 120,Unnamed: 121,Children in single-parent households,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Social associations,Unnamed: 129,Unnamed: 130,Violent crime,Unnamed: 132,Unnamed: 133,Injury deaths,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Air pollution - particulate matter,Unnamed: 140,Drinking water violations,Unnamed: 142,Severe housing problems,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Driving alone to work,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156,Long commute - driving alone,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161
0,FIPS,State,County,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,Z-Score,YPLL Rate (Black),YPLL Rate (Hispanic),YPLL Rate (White),% Fair/Poor,95% CI - Low,95% CI - High,Z-Score,Physically Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Mentally Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Unreliable,% LBW,95% CI - Low,95% CI - High,Z-Score,% LBW (Black),% LBW (Hispanic),% LBW (White),% Smokers,95% CI - Low,95% CI - High,Z-Score,% Obese,95% CI - Low,95% CI - High,Z-Score,Food Environment Index,Z-Score,% Physically Inactive,95% CI - Low,95% CI - High,Z-Score,% With Access,Z-Score,% Excessive Drinking,95% CI - Low,95% CI - High,Z-Score,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Alcohol-Impaired,95% CI - Low,95% CI - High,Z-Score,# Chlamydia Cases,Chlamydia Rate,Z-Score,Teen Birth Rate,95% CI - Low,95% CI - High,Z-Score,Teen Birth Rate (Black),Teen Birth Rate (Hispanic),Teen Birth Rate (White),# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Z-Score,# Primary Care Physicians,PCP Rate,PCP Ratio,Z-Score,# Dentists,Dentist Rate,Dentist Ratio,Z-Score,# Mental Health Providers,MHP Rate,MHP Ratio,Z-Score,Preventable Hosp. Rate,Z-Score,Preventable Hosp. Rate (Black),Preventable Hosp. Rate (Hispanic),Preventable Hosp. Rate (White),% Screened,Z-Score,% Screened (Black),% Screened (Hispanic),% Screened (White),% Vaccinated,Z-Score,% Vaccinated (Black),% Vaccinated (Hispanic),% Vaccinated (White),Cohort Size,Graduation Rate,Z-Score,# Some College,Population,% Some College,95% CI - Low,95% CI - High,Z-Score,# Unemployed,Labor Force,% Unemployed,Z-Score,% Children in Poverty,95% CI - Low,95% CI - High,Z-Score,% Children in Poverty (Black),% Children in Poverty (Hispanic),% Children in Poverty (White),80th Percentile Income,20th Percentile Income,Income Ratio,Z-Score,# Single-Parent Households,# Households,% Single-Parent Households,95% CI - Low,95% CI - High,Z-Score,# Associations,Association Rate,Z-Score,Annual Average Violent Crimes,Violent Crime Rate,Z-Score,# Injury Deaths,Injury Death Rate,95% CI - Low,95% CI - High,Z-Score,Average Daily PM2.5,Z-Score,Presence of violation,Z-Score,% Severe Housing Problems,95% CI - Low,95% CI - High,Severe Housing Cost Burden,Overcrowding,Inadequate Facilities,Z-Score,% Drive Alone,95% CI - Low,95% CI - High,Z-Score,% Drive Alone (Black),% Drive Alone (Hispanic),% Drive Alone (White),# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low,95% CI - High,Z-Score
1,36000,New York,NaN,5427.82,5391.42,5464.21,NaN,NaN,NaN,NaN,16.1051,15.3045,16.9392,NaN,3.57185,3.41524,3.72847,NaN,3.59262,3.421,3.76423,NaN,NaN,7.95536,7.91416,7.99657,NaN,NaN,NaN,NaN,14.1756,13.4236,14.9624,NaN,25.7,NaN,NaN,NaN,9.1,NaN,24.5,NaN,NaN,NaN,92.9061,NaN,18.7519,17.8706,19.6663,NaN,1137,5419,20.9817,20.3171,21.6533,NaN,109433,552.8,NaN,16.4908,16.4,16.6,NaN,NaN,NaN,NaN,1151995,7.06769,6.94854,7.18683,NaN,16460,83.3617,1200:1,NaN,16134,81.2821,1230:1,NaN,53126,267.645,374:1,NaN,4141,NaN,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,207863,81.8,NaN,3634076,5368675,67.6904,67.4108,67.97,NaN,455474,9704700,4.69333,NaN,19.9,19.3043,20.4957,NaN,NaN,NaN,NaN,132486,23178,5.71602,NaN,1425390,4151439,34.3348,34.0023,34.6674,NaN,15718,7.96038,NaN,74841.5,379.026,NaN,46707,47.2801,46.9,47.7,NaN,8.5,NaN,NaN,NaN,24.2402,24.1382,24.3422,NaN,NaN,NaN,NaN,52.9286,52.785,53.0722,NaN,NaN,NaN,NaN,4906304,37.6,37.3617,37.8383,NaN
2,36001,New York,Albany,5690.44,5380.96,5999.92,-0.685497,8849.76,5100.11,5492.26,13.4795,13.1508,13.8222,-0.743806,3.30162,3.19537,3.40964,-1.25748,3.79227,3.6753,3.9193,-0.383732,NaN,8.35382,7.98447,8.72317,1.31404,13.0404,8.8968,6.89091,15.1486,14.73,15.5526,-0.894029,26.9,24.2,29.7,-0.787949,8.1,0.521259,21.7,19.6,24,-0.96858,92.2726,-0.882666,20.028,19.4923,20.5585,-0.122513,24,100,24,18.8993,29.3604,0.14822,1760,568.9,1.17345,12.0273,11.3,12.8,-0.860709,32.0995,25.3371,6.21899,10741,4.36614,3.77039,4.96188,-1.1616,325,105.23,950:1,-1.44259,278,89.7898,1114:1,-1.20834,1035,334.289,299:1,-1.25044,4219,-0.170784,7069,5455,3784,45,0.0389314,41,41,46,51,-0.727078,36,44,53,3014,84.4061,0.0923663,57547,75122,76.6047,74.2907,78.9188,-1.80667,6816,159950,4.26133,-1.18934,13.2,9.62553,16.7745,-1.04127,32.3056,36.3286,7.65365,124921,25700,4.86074,0.233733,19962,57045,34.9934,32.68,37.3069,0.200009,449,14.538,-0.981283,1073.5,348.218,0.902746,682,44.2009,40.9,47.5,-1.28984,9.1,0.494024,Yes,0.709883,15.5286,14.776,16.2811,14.6421,0.931551,0.672337,-0.290041,76.9819,76.1478,77.816,0.156926,59.2346,62.5402,84.1563,120111,20.8,19.7545,21.8455,-1.213
3,36003,New York,Allegany,6617.28,5762.79,7471.77,0.237029,NaN,NaN,NaN,14.9084,14.4171,15.419,-0.149671,4.00924,3.85152,4.17263,0.690177,4.33313,4.15865,4.52041,1.51558,NaN,7.03726,6.17522,7.89929,-0.215569,NaN,NaN,NaN,20.913,20.2404,21.6191,1.08748,34.6,30.7,38.7,0.895124,8.2,0.30864,29.2,25.7,33.1,1.31882,56.5439,1.4325,21.2721,20.5357,22.0891,0.544883,5,18,27.7778,15.2184,41.0167,0.524985,104,219.1,-0.758877,15.3085,13.3,17.3,-0.399194,NaN,NaN,NaN,1936,5.58585,4.75181,6.41989,-0.214074,19,40.3594,2478:1,0.711744,14,29.8546,3350:1,0.928311,90,191.922,521:1,0.0684698,3708,-0.892414,NaN,NaN,NaN,49,-0.765651,NaN,NaN,NaN,46,0.622588,31,NaN,46,502,87.8486,-0.56574,5669,9521,59.5421,55.6422,63.442,0.370617,1331,19858,6.70259,1.77807,25,19.1617,30.8383,0.957133,NaN,44.9761,25.1575,82991,20161,4.11641,-0.672688,3083,9490,32.4868,28.4224,36.5512,-0.155934,79,16.781,-1.60329,91.5,195.029,-0.213819,126,53.1023,43.8,62.4,-0.428509,8.5,-0.126844,Yes,0.709883,14.7115,13.2818,16.1412,11.1448,2.07821,2.35165,-0.435151,75.0546,73.5767,76.5325,0.0348147,14.2361,30.3887,74.2436,14785,29.3,27.3567,31.2433,-0.444022
4,36005,New York,Bronx,6650.65,6509.46,6791.85,0.270245,8212.28,5524.12,7749.08,26.8377,26.3499,27.325,4.81056,4.85563,4.72809,4.97841,3.0198,4.29357,4.17129,4.41246,1.37665,NaN,9.38152,9.23373,9.52931,2.50803,11.5272,8.42725,7.30474,16.1729,15.7942,16.5797,-0.541903,29.9,27.4,32.6,-0.132206,7.8,1.15912,30.9,28.5,33.4,1.8373,100,-1.38339,16.127,15.6881,16.6049,-2.21525,31,216,14.3519,11.1946,17.8285,-0.814008,17043,1171,4.49951,28.7166,28.2,29.3,1.48672,24.0718,34.0253,10.0498,116497,9.3856,8.67071,10.1005,2.73772,837,57.4973,1739:1,0.142601,734,49.8926,2004:1,0.213969,2744,186.519,536:1,0.118521,5528,1.67777,6004,6796,4306,33,2.45268,32,32,37,37,3.05199,32,33,44,14750,67.5119,3.32206,209419,413152,50.6881,49.7413,51.635,1.50043,38533,621649,6.19851,1.16536,39.3,36.2021,42.3979,3.37892,38.4684,46.3884,17.5294,82595,12606,6.55204,2.29335,220320,359925,61.2128,59.9514,62.4741,3.92322,370,2.5417,2.34539,8486,586.058,2.63631,3090,42.6842,41.2,44.2,-1.4366,10.3,1.73576,Yes,0.709883,39.4143,38.8417,39.9869,31.3642,12.0881,0.919777,3.95215,22.9977,22.4588,23.5365,-3.26341,34.0847,27.0765,58.6529,132665,52.4,50.6529,54.1471,1.64578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,6609.15,5833.86,7384.43,0.228932,NaN,NaN,NaN,14.276,13.858,14.7263,-0.412619,3.85147,3.69737,4.01318,0.255919,3.95699,3.79341,4.12828,0.194707,NaN,7.19269,6.40727,7.97811,-0.0349869,NaN,NaN,NaN,19.0226,18.4307,19.6053,0.437655,34.8,31,38.5,0.93884,8.4,-0.116597,24.4,21.5,27.3,-0.145115,66.219,0.805568,19.6009,18.9872,20.2184,-0.351633,9,37,24.3243,15.7971,33.4999,0.180566,149,239.4,-0.646738,25.1373,22.3,28,0.983272,NaN,NaN,NaN,2636,5.50497,4.67093,6.33901,-0.276905,19,30.7443,3253:1,1.03106,14,22.7199,4401:1,1.18266,84,136.319,734:1,0.583583,3817,-0.738485,NaN,NaN,NaN,44,0.240077,NaN,44,44,44,1.16245,29,46,45,690,79.5652,1.0178,8212,14867,55.2364,50.9434,59.5295,0.92004,1338,28504,4.69408,-0.663328,17.6,12.7149,22.4851,-0.296099,47.9167,43.0137,16.8515,96145,23698,4.05709,-0.744926,4517,11859,38.0892,32.5974,43.581,0.639618,66,10.6796,0.088677,88,141.089,-0.606981,178,57.2136,48.8,65.6,-0.0306853,8.9,0.287068,Yes,0.709883,16.0099,14.085,17.9348,14.4663,1.44419,0.804621,-0.204552,81.4021,79.4247,83.3794,0.43698,NaN,NaN,NaN,22782,37.9,34.8321,40.9679,0.334001
60,36117,New York,Wayne,7112.3,6444.18,7780.43,0.729743,16976.7,NaN,6956.4,16.2759,15.8299,16.7883,0.418941,4.09726,3.94449,4.25073,0.932446,4.30443,4.1371,4.46972,1.41481,NaN,7.22839,6.61505,7.84173,0.00649091,10.4167,7.56757,7.09877,21.4401,20.7992,22.123,1.26865,36.4,32.8,40.2,1.28857,8.6,-0.541835,29.4,25.9,32.9,1.37982,63.0647,1.00996,18.7829,18.1943,19.4423,-0.790456,8,54,14.8148,8.51401,22.3724,-0.767836,243,265.7,-0.501454,20.5469,18.6,22.5,0.337617,34.0136,32.3993,19.3081,3992,5.34533,4.63044,6.06022,-0.400919,25,27.5337,3632:1,1.13768,45,49.6305,2015:1,0.223312,85,93.7465,1067:1,0.977984,5846,2.12685,2713,2732,5947,45,0.0389314,34,36,46,51,-0.727078,47,44,52,1164,87.1993,-0.441614,12801,20071,63.7786,60.0371,67.5201,-0.169987,2221,44024,5.04498,-0.236802,16.3,12.4872,20.1128,-0.516262,44.584,26.8347,14.5055,97967,25638,3.82116,-1.03223,6576,19682,33.4112,29.4712,37.3513,-0.0246656,100,11.0135,-0.00390145,163,178.443,-0.334711,265,57.9313,51,64.9,0.0387694,8.6,-0.023366,No,-1.38596,12.3783,11.0565,13.7002,10.9241,1.48047,0.740233,-0.84953,84.5818,83.0724,86.0912,0.638441,68.4713,74.5819,83.4474,35839,38.8,36.5487,41.0513,0.415422
61,36119,New York,Westchester,4144.31,3997,4291.61,-2.22443,6855.79,3038.64,4055.68,14.2811,13.981,14.5882,-0.410493,3.23995,3.14723,3.32961,-1.42723,3.35718,3.26551,3.45471,-1.91166,NaN,7.97728,7.78176,8.1728,0.876567,12.2131,7.04117,6.96724,11.3798,11.0795,11.6748,-2.18953,20.7,18.7,22.8,-2.14315,9.2,-1.81755,20.9,19,23.1,-1.21257,99.601,-1.35753,19.2357,18.8076,19.6393,-0.54753,41,199,20.603,17.0752,24.3256,-0.190568,3804,389.6,0.182981,9.72641,9.3,10.1,-1.18434,16.9458,23.938,1.4762,61342,7.66086,7.06512,8.25661,1.39788,1351,138.629,721:1,-2.55175,1071,109.259,915:1,-1.90238,3560,363.175,275:1,-1.51804,3976,-0.513946,6259,4788,3545,45,0.0389314,40,40,47,49,-0.187212,35,39,53,11163,89.5548,-0.891912,170698,237677,71.8193,70.5747,73.0639,-1.19603,22053,484107,4.5554,-0.831898,10.6,8.57447,12.6255,-1.48159,21.7817,21.4586,3.61114,197122,32290,6.10474,1.74864,56246,218117,25.7871,24.5946,26.9796,-1.10731,829,8.50656,0.691282,2148.5,220.606,-0.0273952,1960,40.2248,38.4,42,-1.67458,10.4,1.83924,Yes,0.709883,24.7247,24.128,25.3214,21.4073,4.15369,0.741521,1.34322,57.5601,56.8767,58.2434,-1.0736,55.3922,53.6803,78.4925,269784,40.8,39.782,41.818,0.596358
62,36121,New York,Wyoming,6255.49,5388.44,7122.54,-0.123074,NaN,NaN,NaN,16.1984,15.7152,16.699,0.38673,3.86337,3.71887,4.0033,0.288682,3.83894,3.69169,3.99162,-0.219869,NaN,6.15148,5.22808,7.07488,-1.24468,NaN,NaN,NaN,21.9264,21.2586,22.5908,1.43582,35.8,31.6,39.9,1.15742,8.3,0.0960214,24.6,21.1,28.2,-0.0841174,68.2861,0.671624,19.4482,18.8099,20.11,-0.433534,4,22,18.1818,7.90486,30.7479,-0.432038,96,234.1,-0.676016,13.9202,11.3,16.5,-0.594456,NaN,NaN,NaN,1632,5.35662,4.52257,6.19066,-0.392153,17,41.6759,2399:1,0.668025,19,46.9217,2131:1,0.31988,81,200.035,500:1,-0.00668445,4997,0.927901,NaN,NaN,NaN,47,-0.36336,NaN,NaN,NaN,51,-0.727078,NaN,NaN,NaN,339,93.8053,-1.70449,5528,10486,52.7179,48.9771,56.4587,1.24142,1029,18086,5.68948,0.546615,15,11.4255,18.5745,-0.736425,61.1111,50.5976,15.8217,94180,24259,3.88227,-0.95782,2670,8043,33.1966,28.0135,38.3796,-0.0551493,66,16.18,-1.43664,45.5,110.996,-0.826323,133,64.873,53.8,75.9,0.710466,8.8,0.18359,Yes,0.709883,8.93253,7.70738,10.1577,7.78772,0.912258,0.316756,-1.46152,83.6417,82.2383,85.0452,0.57888,NaN,NaN,NaN,15007,37.9,34.9645,40.8355,0.334001
63,36123,New York,Yates,6583.43,5335.24,7831.61,0.203333,NaN,NaN,NaN,12.8683,12.3943,13.3333,-0.997947,3.37772,3.21751,3.54384,-1.04802,3.79833,3.61498,3.99186,-0.362449,NaN,4.97906,4.05941,5.89871,-2.60681,NaN,NaN,NaN,16.2706,15.6499,16.9158,-0.508337,29.7,25.6,34.3,-0.175922,8.9,-1.17969,29.4,25.4,33.6,1.37982,49.4437,1.89258,19.0021,18.3088,19.7613,-0.672893,4,10,40,22.7274,55.69,1.74393,58,231.6,-0.689826,13.0223,10.5,16,-0.720753,NaN,NaN,NaN,1816,9.50586,8.07608,10.9356,2.83114,11,44.1359,2266:1,0.586327,12,48.0866,2080:1,0.278353,27,108.195,924:1,0.844134,4144,-0.276698,NaN,NaN,NaN,48,-0.564506,NaN,NaN,NaN,51,-0.727078,NaN,29,51,214,78.5047,1.22055,2537,4984,50.9029,45.2386,56.5671,1.47302,523,11702,4.46932,-0.936526,24.4,17.3702,31.4298,0.85552,34.4828,25.9259,18.2515,102587,22185,4.62416,-0.0543662,1419,5557,25.5354,20.0804,30.9903,-1.14306,36,14.4445,-0.955355,19,76.0471,-1.08106,72,57.4667,45,72.4,-0.00619379,7.9,-0.747712,Yes,0.709883,16.401,13.8177,18.9844,13.7022,2.62211,0.771208,-0.135087,67.7294,64.8711,70.5876,-0.429295,NaN,NaN,NaN,7478,31,27.6342,34.3658,-0.290226

In [ ]:
#Deleting columns
to_remove=df3.iloc[:,np.r_[1:3,4:10,11:34,35:38,39:98,100:103,104:162]]
df3c=df3.drop(columns=to_remove)

#Deleting rows
df3c=df3c.drop([0,1])

#Renaming columns
new_col3= {'Unnamed: 0':'fips',
          'Premature death':'yppl',
          'Poor or fair health':'%poor_fair_health',
          'Adult obesity':'%adult_obesity',
          'Food environment index':'food_environment_index',
          'High school graduation': 'graduation_cohort',
          'Unnamed: 99': 'graduation_rate',
          'Unnamed: 103':'%some_college'}

df3c=df3c.rename(columns=new_col3)
df3c

,fips,yppl,%poor_fair_health,%adult_obesity,food_environment_index,graduation_cohort,graduation_rate,%some_college
2,36001,5690.44,13.4795,26.9,8.1,3014,84.4061,76.6047
3,36003,6617.28,14.9084,34.6,8.2,502,87.8486,59.5421
4,36005,6650.65,26.8377,29.9,7.8,14750,67.5119,50.6881
5,36007,7609.17,17.2002,28.3,8.1,2205,82.9478,66.5102
6,36009,7397.16,18.5291,36.5,8.2,1041,85.0144,55.0563
...,...,...,...,...,...,...,...,...
59,36115,6609.15,14.276,34.8,8.4,690,79.5652,55.2364
60,36117,7112.3,16.2759,36.4,8.6,1164,87.1993,63.7786
61,36119,4144.31,14.2811,20.7,9.2,11163,89.5548,71.8193
62,36121,6255.49,16.1984,35.8,8.3,339,93.8053,52.7179
63,36123,6583.43,12.8683,29.7,8.9,214,78.5047,50.9029

### 4th Sheet: Additional Measure Data

In [ ]:
df4=pd.read_excel("2019_health_r.xlsx",sheet_name='Additional Measure Data')
df4

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Life expectancy,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Premature age-adjusted mortality,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Child mortality,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Infant mortality,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Frequent physical distress,Unnamed: 31,Unnamed: 32,Frequent mental distress,Unnamed: 34,Unnamed: 35,Diabetes prevalence,Unnamed: 37,Unnamed: 38,HIV prevalence,Unnamed: 40,Food insecurity,Unnamed: 42,Limited access to healthy foods,Unnamed: 44,Drug overdose deaths,Unnamed: 46,Motor vehicle crash deaths,Unnamed: 48,Unnamed: 49,Unnamed: 50,Insufficient sleep,Unnamed: 52,Unnamed: 53,Uninsured adults,Unnamed: 55,Unnamed: 56,Unnamed: 57,Uninsured children,Unnamed: 59,Unnamed: 60,Unnamed: 61,Other primary care providers,Unnamed: 63,Disconnected youth,Median household income,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Children eligible for free or reduced price lunch,Residential segregation - black/white,Residential segregation - non-white/white,Homicides,Unnamed: 75,Unnamed: 76,Firearm fatalities,Unnamed: 78,Unnamed: 79,Unnamed: 80,Homeownership,Unnamed: 82,Unnamed: 83,Unnamed: 84,Severe housing cost burden,Unnamed: 86,Unnamed: 87,Unnamed: 88,Demographics,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110
0,FIPS,State,County,Life Expectancy,95% CI - Low,95% CI - High,Life Expectancy (Black),Life Expectancy (Hispanic),Life Expectancy (White),# Deaths,Age-Adjusted Mortality,95% CI - Low,95% CI - High,Age-Adjusted Mortality (Black),Age-Adjusted Mortality (Hispanic),Age-Adjusted Mortality (White),# Deaths,Child Mortality Rate,95% CI - Low,95% CI - High,Child Mortality Rate (Black),Child Mortality Rate (Hispanic),Child Mortality Rate (White),# Deaths,Infant Mortality Rate,95% CI - Low,95% CI - High,Infant Mortality Rate (Black),Infant Mortality Rate (Hispanic),Infant Mortality Rate (White),% Frequent Physical Distress,95% CI - Low,95% CI - High,% Frequent Mental Distress,95% CI - Low,95% CI - High,% Diabetic,95% CI - Low,95% CI - High,# HIV Cases,HIV Prevalence Rate,# Food Insecure,% Food Insecure,# Limited Access,% Limited Access,# Drug Overdose Deaths,Drug Overdose Mortality Rate,# Motor Vehicle Deaths,MV Mortality Rate,95% CI - Low,95% CI - High,% Insufficient Sleep,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Other PCP Rate,Other PCP Ratio,% Disconnected Youth,Household Income,95% CI - Low,95% CI - High,Household income (Black),Household income (Hispanic),Household income (White),% Free or Reduced Lunch,Segregation index,Segregation Index,Homicide Rate,95% CI - Low,95% CI - High,# Firearm Fatalities,Firearm Fatalities Rate,95% CI - Low,95% CI - High,# Homeowners,% Homeowners,95% CI - Low,95% CI - High,# Households with Severe Cost Burden,% Severe Housing Cost Burden,95% CI - Low,95% CI - High,Population,% < 18,% 65 and over,# African American,% African American,# American Indian/Alaskan Native,% American Indian/Alaskan Native,# Asian,% Asian,# Native Hawaiian/Other Pacific Islander,% Native Hawaiian/Other Pacific Islander,# Hispanic,% Hispanic,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural
1,36000,New York,NaN,81.1758,81.1346,81.217,NaN,NaN,NaN,189569,278.4,277.1,279.7,NaN,NaN,NaN,6631,39.5296,38.6,40.5,NaN,NaN,NaN,7891,4.73901,4.6,4.8,NaN,NaN,NaN,10.7253,10.0987,11.3858,10.7869,10.0706,11.5477,9.8,NaN,NaN,128681,768.8,2352940,11.9,443539,2.28887,10313,17.3647,8315,6.03309,5.9,6.2,36.7114,35.6313,37.805,1052286,8.63189,8.39359,8.87019,111308,2.57166,2.33336,2.80996,105.923,944:1,6.61604,64783,64187.3,65378.7,NaN,NaN,NaN,52.6388,74.3582,61.8144,3.4,3.3,3.5,4259,4.3,4.2,4.4,3942483,53.9866,53.7221,54.2511,1441746,20.3684,20.2442,20.4926,19849399,20.9301,15.9309,2889100,14.5551,193229,0.973475,1806646,9.10177,26943,0.135737,3811945,19.2043,10972959,55.2811,1338707,7.1891,7.11725,7.26095,51.4471,2349997,12.1271
2,36001,New York,Albany,80.1163,79.7998,80.4328,77.0886,84.981,80.2934,3202,298.4,287.8,309.1,461.839,257.861,288.629,108,46.5604,37.8,55.3,78.1948,NaN,40.6367,153,7.2112,6.1,8.4,19.3883,NaN,4.54513,10.0623,9.79905,10.3252,10.9833,10.7392,11.2216,9.2,7.9,10.6,1004,375.1,37650,12.2,14540.1,4.77973,117,12.6099,115,5.34393,4.4,6.3,33.8319,33.2412,34.4308,9635,5.09629,4.3814,5.81119,1281,2.12079,1.52505,2.71654,167.952,595:1,4.09746,65659,61977.3,69340.7,31802,37323,70591,35.4484,59.328,43.947,2.7,2,3.5,66,4.3,3.3,5.4,71274,56.8482,56.1125,57.5839,18395,14.96,14.0498,15.8703,309612,18.5745,16.407,39189,12.6575,894,0.288748,21674,7.00037,216,0.0697647,18461,5.96262,222742,71.9423,5330,1.81952,1.55518,2.08387,51.6343,29496,9.69612
3,36003,New York,Allegany,78.4867,77.6978,79.2755,NaN,NaN,NaN,596,346,316.6,375.4,NaN,NaN,NaN,14,36.1785,19.8,60.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.2564,11.8741,12.6564,12.8204,12.479,13.1976,11,9.1,13.2,37,91,5900,12.4,1464.32,2.9917,10,7.07049,27,8.07385,5.3,11.7,35.8354,34.9835,36.7037,1619,6.41137,5.33903,7.48371,344,3.45451,2.26302,4.646,70.3715,1421:1,6.13512,46491,43699.3,49282.7,42188,19091,45576,55.5556,NaN,35.4012,NaN,NaN,NaN,30,12.6,8.5,18,13463,74.2827,73.4847,75.0807,1970,11.2552,9.83631,12.6741,46894,20.3544,18.3606,592,1.26242,140,0.298546,624,1.33066,17,0.036252,742,1.58229,44268,94.4001,261,0.580749,0.264438,0.897059,49.1364,38540,78.7398
4,36005,New York,Bronx,80.3598,80.1795,80.54,78.9357,82.7369,78.6078,14817,343.9,338.4,349.5,407.837,290.316,391.67,639,43.4745,40.1,46.8,62.0768,29.53,52.3265,778,5.08726,4.7,5.4,7.06376,3.4886,4.63374,15.8672,15.5547,16.1909,14.4661,14.1917,14.7553,13.1,11.7,14.6,26666,2258.2,231590,16.1,12.7411,0.000919861,915,20.8793,403,4.01407,3.6,4.4,39.8963,39.3431,40.485,109518,12.316,11.3628,13.2692,7908,2.13138,1.65478,2.60797,100.329,997:1,10.2027,37377,35763.7,38990.3,39259,31073,60892,82.0618,47.7266,40.3753,7.1,6.6,7.6,320,4.4,3.9,4.9,97658,19.7147,19.2828,20.1466,150479,31.6407,31.0235,32.2579,1471160,24.863,12.3245,431776,29.3494,43002,2.923,66509,4.52085,6081,0.413347,826176,56.1581,135770,9.22877,214442,15.9123,15.5521,16.2726,52.8399,39,0.00281566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,79.0474,78.3366,79.7581,79.8584,82.0956,78.9614,796,332,307.7,356.3,NaN,NaN,NaN,21,43.5766,27,66.6,NaN,NaN,NaN,22,5.3243,3.3,8.1,NaN,NaN,NaN,11.6922,11.3502,12.0552,11.7862,11.4644,12.1211,12,10.1,14,194,361.2,6620,10.6,2709.72,4.28644,10,5.38648,50,11.436,8.5,15.1,36.0967,35.353,36.8631,2367,6.53723,5.46489,7.60957,302,2.45369,1.7388,3.16858,51.9312,1926:1,9.34256,53609,48188.9,59029.1,NaN,32969,52594,48.5191,65.369,25.1056,2.7,1.4,4.8,22,7.1,4.4,10.7,17431,72.6655,71.3276,74.0034,3255,14.006,12.2685,15.7436,61620,19.2064,18.8916,1823,2.95846,203,0.329438,355,0.576112,22,0.0357027,1720,2.7913,56908,92.3531,274,0.46337,0.221566,0.705174,48.2425,42923,67.8989
60,36117,New York,Wayne,78.6991,78.0864,79.3118,73.1618,93.7974,78.709,1197,342.4,321.9,362.9,677.713,NaN,337.494,42,52.7314,38,71.3,NaN,NaN,NaN,39,5.59701,4,7.7,NaN,NaN,NaN,12.1482,11.806,12.527,12.4121,12.0891,12.7407,11.4,9.5,13.6,119,153.8,9020,9.8,3271.64,3.48893,25,9.16039,86,13.3574,10.7,16.5,36.1929,35.4111,37.0021,3475,6.2994,5.34621,7.25259,572,2.77011,1.93607,3.60415,46.3218,2159:1,8.46224,52709,49029.7,56388.3,32790,40341,54428,48.1605,51.2956,39.0756,1.9,1,3.3,24,5.2,3.4,7.8,28109,76.8467,75.301,78.3924,3818,10.6872,9.38681,11.9876,90670,21.5617,18.2651,2534,2.79475,360,0.397044,680,0.749972,38,0.0419102,4060,4.47778,81506,89.893,681,0.788304,0.523166,1.05344,50.3926,56917,60.6972
61,36119,New York,Westchester,83.5252,83.3378,83.7125,80.931,90.3505,83.218,7174,212.3,207.2,217.3,341.642,147.168,209.223,253,28.7305,25.2,32.3,65.7409,28.8163,17.2608,301,4.07544,3.6,4.5,8.69198,3.69679,2.30064,9.93365,9.70786,10.1375,10.1762,9.98495,10.3671,7.9,6.8,9,3299,402.8,75080,7.7,13090,1.37919,403,13.7487,297,4.37396,3.9,4.9,33.1018,32.6086,33.5947,54951,9.40372,8.56968,10.2378,7037,3.0824,2.36751,3.7973,75.4914,1325:1,6.01497,90483,87044.4,93921.6,56859,57809,111583,36.4386,61.6029,45.4576,2.2,1.8,2.5,126,2.6,2.1,3,212731,61.5034,60.9753,62.0315,70925,21.0875,20.4826,21.6925,980244,22.1862,16.5975,134614,13.7327,9314,0.950172,63995,6.52848,1243,0.126805,243720,24.8632,523289,53.3835,58326,6.34166,6.05256,6.63075,51.5489,31069,3.27348
62,36121,New York,Wyoming,78.7162,77.906,79.5264,80.2855,NaN,78.3059,509,325.8,296.5,355.2,NaN,NaN,NaN,10,32.0873,15.4,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.2008,10.8669,11.5429,11.6305,11.3228,11.9439,11.5,9.5,13.8,161,452.7,4300,10.4,2557.4,6.06666,18,14.7183,29,10.0397,6.7,14.4,36.1517,35.3324,36.9498,1422,6.23056,5.15822,7.3029,231,2.85891,1.90572,3.8121,51.8608,1928:1,11.6343,53986,48685.1,59286.9,NaN,NaN,NaN,44.2733,NaN,18.1225,NaN,NaN,NaN,22,10.7,6.7,16.2,11897,75.8447,74.3224,77.367,1472,9.71681,8.24316,11.1905,40493,18.9243,17.198,2139,5.28239,163,0.402539,224,0.553182,12,0.0296348,1367,3.37589,36347,89.7612,201,0.518215,0.171754,0.864676,45.6968,27014,64.0826
63,36123,New York,Yates,78.9676,77.8733,80.0619,NaN,NaN,NaN,281,300.2,262.3,338.1,NaN,NaN,NaN,11,48.5801,24.3,86.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.8201,10.469,11.1712,11.9645,11.6352,12.3303,13.5,11.1,16.3,7,33.2,2540,10.1,126.743,0.500011,13,17.3505,11,6.24688,3.1,11.2,28.7244,27.89,29.5637,1408,10.2871,8.4999,12.0744,428,7.45255,4.95042,9.95468,64.1154,1560:1,13.769,49198,43826.8,54569.2,NaN,65298,52513,45.6645,51.1891,20.6669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7196,77.0615,75.4311,78.6918,1231,13.483,10.7427,16.2233,24955,22.1038,20.012,232,0.929673,77,0.308555,172,0.689241,5,0.0200361,584,2.34021,23673,94.8628,185,0.785029,0.286923,1.28314,51.2563,18054,71.2246

In [ ]:
#Remove columns
to_remove=df4.iloc[:,np.r_[1:3,4:36,37:42,43,45:65,66:71,72:93,94,96,98,100,102,104:111]]
df4c=df4.drop(columns=to_remove)

#Remove rows
df4c=df4c.drop([0,1])

#Rename columns
new_col4={'Unnamed: 0': 'fips',
          'Life expectancy':'life_expectancy',
          'Diabetes prevalence':'%diabetes',
          'Unnamed: 42':'%food_insecure',
          'Unnamed: 44':'%limited_access',
          'Median household income':'household_income',
          'Children eligible for free or reduced price lunch':'%lunch_aid',
          'Unnamed: 93':'%african_american',
          'Unnamed: 95':'%american_indian',
          'Unnamed: 97':'%asian',
          'Unnamed: 99':'%pacific_islander',
          'Unnamed: 101':'%hispanic',
          'Unnamed: 103':'%white'
    
}
df4c=df4c.rename(columns=new_col4)
df4c

,fips,life_expectancy,%diabetes,%food_insecure,%limited_access,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
2,36001,80.1163,9.2,12.2,4.77973,65659,35.4484,12.6575,0.288748,7.00037,0.0697647,5.96262,71.9423
3,36003,78.4867,11,12.4,2.9917,46491,55.5556,1.26242,0.298546,1.33066,0.036252,1.58229,94.4001
4,36005,80.3598,13.1,16.1,0.000919861,37377,82.0618,29.3494,2.923,4.52085,0.413347,56.1581,9.22877
5,36007,78.5428,10.6,13,3.24067,47910,52.82,5.27838,0.265442,4.66848,0.0661024,4.25431,83.131
6,36009,77.762,12.8,12.5,2.58394,47875,52.9492,1.45059,3.47132,0.840358,0.0310286,2.08926,90.4988
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,79.0474,12,10.6,4.28644,53609,48.5191,2.95846,0.329438,0.576112,0.0357027,2.7913,92.3531
60,36117,78.6991,11.4,9.8,3.48893,52709,48.1605,2.79475,0.397044,0.749972,0.0419102,4.47778,89.893
61,36119,83.5252,7.9,7.7,1.37919,90483,36.4386,13.7327,0.950172,6.52848,0.126805,24.8632,53.3835
62,36121,78.7162,11.5,10.4,6.06666,53986,44.2733,5.28239,0.402539,0.553182,0.0296348,3.37589,89.7612
63,36123,78.9676,13.5,10.1,0.500011,49198,45.6645,0.929673,0.308555,0.689241,0.0200361,2.34021,94.8628

### Merge 4 sheets

In [ ]:
#Merge first 2
merged_df1=pd.merge(df1c,df2c,on='fips',how='outer')

#Merge second 2
merged_df2=pd.merge(df3c,df4c,on='fips',how='outer')

#Merge all together
rank2019=pd.merge(merged_df1,merged_df2,on='fips',how='outer')

#Keep only counties in NYC
#county_nyc=['New York','Kings','Bronx','Richmond','Queens']
#rank2019=rank2019[rank2019['county_name'].isin(county_nyc)]
rank2019=rank2019.reset_index().drop(columns=['index','health_outcomes_z','health_factors_z','lenght_life_z','quality_life_z'])
rank2019

,fips,state,county_name,health_outcomes_r,health_factors_r,length_life_r,quality_life_r,yppl,%poor_fair_health,%adult_obesity,food_environment_index,graduation_cohort,graduation_rate,%some_college,life_expectancy,%diabetes,%food_insecure,%limited_access,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
0,36087,New York,Rockland,1,6,3,3,4272.9,14.0891,23.7,8.8,3248,84.5443,63.8056,83.3129,8.8,9.2,3.33759,87873,37.1064,11.4779,0.525135,6.49531,0.135921,17.9674,62.692
1,36059,New York,Nassau,2,1,5,13,4300.06,12.253,23.2,9.7,16554,90.7696,74.8459,82.8271,8.5,5.6,0.468288,107465,28.1783,11.5606,0.53289,10.1336,0.0953623,17.1506,59.8515
2,36119,New York,Westchester,3,4,2,19,4144.31,14.2811,20.7,9.2,11163,89.5548,71.8193,83.5252,7.9,7.7,1.37919,90483,36.4386,13.7327,0.950172,6.52848,0.126805,24.8632,53.3835
3,36091,New York,Saratoga,4,2,6,4,4906.76,11.1604,26.4,8.9,2742,90.919,77.947,80.9205,9.3,7.9,3.98443,82732,22.914,1.69444,0.232306,2.94994,0.0508986,3.23097,90.2997
4,36061,New York,New York,5,12,1,30,3984.71,14.5322,15.8,8.3,16235,74.5365,83.7353,84.5163,7,13.3,0,84133,64.5944,12.3724,1.18386,12.9832,0.182432,26.1305,46.6776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,36063,New York,Niagara,58,52,61,59,7710.31,15.8463,33.3,8.2,2431,84.8211,67.1372,77.6271,12.2,12,4.23782,54317,48.0952,7.01043,1.13615,1.13568,0.0411682,2.94613,85.5376
58,36013,New York,Chautauqua,59,55,62,56,8008.55,18.0894,33.1,7.9,1521,83.4977,58.0086,77.4615,11.7,12.4,6.75047,45840,53.8655,2.14497,0.727648,0.700525,0.0503696,7.56629,87.3828
59,36009,New York,Cattaraugus,60,61,54,61,7397.16,18.5291,36.5,8.2,1041,85.0144,55.0563,77.762,12.8,12.5,2.58394,47875,52.9492,1.45059,3.47132,0.840358,0.0310286,2.08926,90.4988
60,36105,New York,Sullivan,61,50,60,60,7685.39,19.0367,32.4,8.3,742,78.4367,54.3998,78.1361,11.3,11,4.66943,52504,57.6809,8.16719,0.703451,1.69173,0.079486,16.1953,71.8262
61,36005,New York,Bronx,62,62,35,62,6650.65,26.8377,29.9,7.8,14750,67.5119,50.6881,80.3598,13.1,16.1,0.000919861,37377,82.0618,29.3494,2.923,4.52085,0.413347,56.1581,9.22877

In [ ]:
#change data types
floats=['yppl','%poor_fair_health','%adult_obesity','food_environment_index','graduation_rate','%some_college','life_expectancy','%diabetes','%food_insecure',
        '%limited_access','%lunch_aid','%african_american','%american_indian','%asian','%pacific_islander','%hispanic','%white']

ints=['fips','health_outcomes_r','health_factors_r','length_life_r','quality_life_r','graduation_cohort','household_income']

rank2019[floats]=rank2019[floats].astype(float)
rank2019[ints]=rank2019[ints].astype(int)

#Save and export
pd.set_option("display.precision", 4)
rank2019
rank2019.to_csv('rank2019.csv',encoding='utf-8',index=False)

## Cleaning 2020 data

Resulting dataframe **rank2020**

### 1st sheet: Outcomes & Factors Rankings

In [ ]:
df5=pd.read_excel('2020_health_r.xlsx',sheet_name='Outcomes & Factors Rankings')
df5

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Health Outcomes,Unnamed: 4,Health Factors,Unnamed: 6
0,FIPS,State,County,Z-Score,Rank,Z-Score,Rank
1,36000,New York,NaN,NaN,NaN,NaN,NaN
2,36001,New York,Albany,-0.1554,25,-0.4705,10
3,36003,New York,Allegany,0.4155,47,0.3878,52
4,36005,New York,Bronx,1.527,62,1.451,62
...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.2851,41,0.1444,38
60,36117,New York,Wayne,0.2625,40,0.06343,33
61,36119,New York,Westchester,-1.127,5,-0.8111,3
62,36121,New York,Wyoming,-0.3553,18,-0.04171,28
63,36123,New York,Yates,-0.08089,27,0.01426,32

In [ ]:
#Remove row
df5c=df5.drop([0,1])

#Renaming columns
new_col1={'Unnamed: 0': 'fips',
         'Unnamed: 1': 'state',
         'Unnamed: 2': 'county_name',
         'Health Outcomes': 'health_outcomes_z',
         'Unnamed: 4': 'health_outcomes_r',
         'Health Factors': 'health_factors_z',
         'Unnamed: 6': 'health_factors_r'}
df5c=df5c.rename(columns=new_col1)
df5c

,fips,state,county_name,health_outcomes_z,health_outcomes_r,health_factors_z,health_factors_r
2,36001,New York,Albany,-0.1554,25,-0.4705,10
3,36003,New York,Allegany,0.4155,47,0.3878,52
4,36005,New York,Bronx,1.527,62,1.451,62
5,36007,New York,Broome,0.6685,52,0.1061,37
6,36009,New York,Cattaraugus,0.8752,57,0.6027,59
...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.2851,41,0.1444,38
60,36117,New York,Wayne,0.2625,40,0.06343,33
61,36119,New York,Westchester,-1.127,5,-0.8111,3
62,36121,New York,Wyoming,-0.3553,18,-0.04171,28
63,36123,New York,Yates,-0.08089,27,0.01426,32

### 2nd sheet: Outcomes & Factors SubRankings

In [ ]:
df6=pd.read_excel('2020_health_r.xlsx',sheet_name='Outcomes & Factors SubRankings')
df6

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Length of Life,Unnamed: 4,Quality of Life,Unnamed: 6,Health Behaviors,Unnamed: 8,Clinical Care,Unnamed: 10,Social & Economic Factors,Unnamed: 12,Physical Environment,Unnamed: 14
0,FIPS,State,County,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank
1,36000,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36001,New York,Albany,-0.3078,15,0.1524,44,-0.08385,18,-0.1493,5,-0.2597,8,0.02234,39
3,36003,New York,Allegany,0.3826,49,0.03285,34,0.1536,46,0.08581,50,0.1394,48,0.008931,34
4,36005,New York,Bronx,0.1053,36,1.421,62,0.1165,43,0.3523,62,0.9336,62,0.04911,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.2251,42,0.05996,37,0.01703,31,0.08837,51,0.0008418,26,0.03815,53
60,36117,New York,Wayne,0.3183,45,-0.05576,26,0.1154,42,0.07696,48,-0.1534,15,0.02451,44
61,36119,New York,Westchester,-1.046,2,-0.08122,23,-0.4792,2,-0.1059,11,-0.3078,6,0.08183,62
62,36121,New York,Wyoming,-0.007962,25,-0.3474,9,0.07713,40,0.03837,41,-0.1732,12,0.01601,36
63,36123,New York,Yates,0.481,52,-0.5619,3,-0.04359,24,0.0648,45,0.003143,27,-0.01009,27

In [ ]:
#Remove columns
to_remove=df6.iloc[:,np.r_[1:3,7:15]]
df6c=df6.drop(columns=to_remove)

#Remove rows
df6c=df6c.drop([0,1])

#Rename columns
new_col6={'Unnamed: 0':'fips',
          'Length of Life':'lenght_life_z',
          'Unnamed: 4':'length_life_r',
          'Quality of Life':'quality_life_z',
          'Unnamed: 6':'quality_life_r'}
df6c=df6c.rename(columns=new_col6)
df6c

     fips lenght_life_z length_life_r quality_life_z quality_life_r
2   36001       -0.3078            15         0.1524             44
3   36003        0.3826            49        0.03285             34
4   36005        0.1053            36          1.421             62
5   36007        0.4449            51         0.2236             49
6   36009        0.3693            47         0.5058             60
..    ...           ...           ...            ...            ...
59  36115        0.2251            42        0.05996             37
60  36117        0.3183            45       -0.05576             26
61  36119        -1.046             2       -0.08122             23
62  36121     -0.007962            25        -0.3474              9
63  36123         0.481            52        -0.5619              3

[62 rows x 5 columns]

### 3rd Sheet: Ranked Measure Data

In [ ]:
df7=pd.read_excel('2020_health_r.xlsx',sheet_name='Ranked Measure Data')
df7

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Premature death,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Poor or fair health,Unnamed: 24,Unnamed: 25,Unnamed: 26,Poor physical health days,Unnamed: 28,Unnamed: 29,Unnamed: 30,Poor mental health days,Unnamed: 32,Unnamed: 33,Unnamed: 34,Low birthweight,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Adult smoking,Unnamed: 56,Unnamed: 57,Unnamed: 58,Adult obesity,Unnamed: 60,Unnamed: 61,Unnamed: 62,Food environment index,Unnamed: 64,Physical inactivity,Unnamed: 66,Unnamed: 67,Unnamed: 68,Access to exercise opportunities,Unnamed: 70,Excessive drinking,Unnamed: 72,Unnamed: 73,Unnamed: 74,Alcohol-impaired driving deaths,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Sexually transmitted infections,Unnamed: 82,Unnamed: 83,Teen births,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Uninsured,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Primary care physicians,Unnamed: 109,Unnamed: 110,Unnamed: 111,Dentists,Unnamed: 113,Unnamed: 114,Unnamed: 115,Mental health providers,Unnamed: 117,Unnamed: 118,Unnamed: 119,Preventable hospital stays,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Mammography screening,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Flu vaccinations,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,High school graduation,Unnamed: 142,Unnamed: 143,Some college,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unemployment,Unnamed: 151,Unnamed: 152,Unnamed: 153,Children in poverty,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,Unnamed: 162,Income inequality,Unnamed: 164,Unnamed: 165,Unnamed: 166,Children in single-parent households,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Social associations,Unnamed: 174,Unnamed: 175,Violent crime,Unnamed: 177,Unnamed: 178,Injury deaths,Unnamed: 180,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Air pollution - particulate matter,Unnamed: 200,Drinking water violations,Unnamed: 202,Severe housing problems,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Driving alone to work,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Long commute - driving alone,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239
0,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,Z-Score,YPLL Rate (AIAN),YPLL Rate (AIAN) 95% CI - Low,YPLL Rate (AIAN) 95% CI - High,YPLL Rate (Asian),YPLL Rate (Asian) 95% CI - Low,YPLL Rate (Asian) 95% CI - High,YPLL Rate (Black),YPLL Rate (Black) 95% CI - Low,YPLL Rate (Black) 95% CI - High,YPLL Rate (Hispanic),YPLL Rate (Hispanic) 95% CI - Low,YPLL Rate (Hispanic) 95% CI - High,YPLL Rate (White),YPLL Rate (White) 95% CI - Low,YPLL Rate (White) 95% CI - High,% Fair or Poor Health,95% CI - Low,95% CI - High,Z-Score,Average Number of Physically Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Average Number of Mentally Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Unreliable,% Low Birthweight,95% CI - Low,95% CI - High,Z-Score,% LBW (AIAN),% LBW (AIAN) 95% CI - Low,% LBW (AIAN) 95% CI - High,% LBW (Asian),% LBW (Asian) 95% CI - Low,% LBW (Asian) 95% CI - High,% LBW (Black),% LBW (Black) 95% CI - Low,% LBW (Black) 95% CI - High,% LBW (Hispanic),% LBW (Hispanic) 95% CI - Low,% LBW (Hispanic) 95% CI - High,% LBW (White),% LBW (White) 95% CI - Low,% LBW (White) 95% CI - High,% Smokers,95% CI - Low,95% CI - High,Z-Score,% Adults with Obesity,95% CI - Low,95% CI - High,Z-Score,Food Environment Index,Z-Score,% Physically Inactive,95% CI - Low,95% CI - High,Z-Score,% With Access to Exercise Opportunities,Z-Score,% Excessive Drinking,95% CI - Low,95% CI - High,Z-Score,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,95% CI - Low,95% CI - High,Z-Score,# Chlamydia Cases,Chlamydia Rate,Z-Score,Teen Birth Rate,95% CI - Low,95% CI - High,Z-Score,Teen Birth Rate (AIAN),Teen Birth Rate (AIAN) 95% CI - Low,Teen Birth Rate (AIAN) 95% CI - High,Teen Birth Rate (Asian),Teen Birth Rate (Asian) 95% CI - Low,Teen Birth Rate (Asian) 95% CI - High,Teen Birth Rate (Black),Teen Birth Rate (Black) 95% CI - Low,Teen Birth Rate (Black) 95% CI - High,Teen Birth Rate (Hispanic),Teen Birth Rate (Hispanic) 95% CI - Low,Teen Birth Rate (Hispanic) 95% CI - High,Teen Birth Rate (White),Teen Birth Rate (White) 95% CI - Low,Teen Birth Rate (White) 95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Z-Score,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,Z-Score,# Dentists,Dentist Rate,Dentist Ratio,Z-Score,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Z-Score,Preventable Hospitalization Rate,Z-Score,Preventable Hosp. Rate (AIAN),Preventable Hosp. Rate (Asian),Preventable Hosp. Rate (Black),Preventable Hosp. Rate (Hispanic),Preventable Hosp. Rate (White),% With Annual Mammogram,Z-Score,% Screened (AIAN),% Screened (Asian),% Screened (Black),% Screened (Hispanic),% Screened (White),% Vaccinated,Z-Score,% Vaccinated (AIAN),% Vaccinated (Asian),% Vaccinated (Black),% Vaccinated (Hispanic),% Vaccinated (White),Cohort Size,High School Graduation Rate,Z-Score,# Some College,Population,% Some College,95% CI - Low,95% CI - High,Z-Score,# Unemployed,Labor Force,% Unemployed,Z-Score,% Children in Poverty,95% CI - Low,95% CI - High,Z-Score,% Children in Poverty (AIAN),% Children in Poverty (Asian),% Children in Poverty (Black),% Children in Poverty (Hispanic),% Children in Poverty (White),80th Percentile Income,20th Percentile Income,Income Ratio,Z-Score,# Single-Parent Households,# Households,% Single-Parent Households,95% CI - Low,95% CI - High,Z-Score,# Associations,Social Association Rate,Z-Score,Annual Average Violent Crimes,Violent Crime Rate,Z-Score,# Injury Deaths,Injury Death Rate,95% CI - Low,95% CI - High,Z-Score,Injury Death Rate (AIAN),Injury Death Rate (AIAN) 95% CI - Low,Injury Death Rate (AIAN) 95% CI - High,Injury Death Rate (Asian),Injury Death Rate (Asian) 95% CI - Low,Injury Death Rate (Asian) 95% CI - High,Injury Death Rate (Black),Injury Death Rate (Black) 95% CI - Low,Injury Death Rate (Black) 95% CI - High,Injury Death Rate (Hispanic),Injury Death Rate (Hispanic) 95% CI - Low,Injury Death Rate (Hispanic) 95% CI - High,Injury Death Rate (White),Injury Death Rate (White) 95% CI - Low,Injury Death Rate (White) 95% CI - High,Average Daily PM2.5,Z-Score,Presence of Water Violation,Z-Score,% Severe Housing Problems,95% CI - Low,95% CI - High,Severe Housing Cost Burden,Severe Housing Cost Burden 95% CI - Low,Severe Housing Cost Burden 95% CI - High,Overcrowding,Overcrowding 95% CI - Low,Overcrowding 95% CI - High,Inadequate Facilities,Inadequate Facilities 95% CI - Low,Inadequate Facilities 95% CI - High,Z-Score,% Drive Alone to Work,95% CI - Low,95% CI - High,Z-Score,% Drive Alone (AIAN),% Drive Alone (AIAN) 95% CI - Low,% Drive Alone (AIAN) 95% CI - High,% Drive Alone (Asian),% Drive Alone (Asian) 95% CI - Low,% Drive Alone (Asian) 95% CI - High,% Drive Alone (Black),% Drive Alone (Black) 95% CI - Low,% Drive Alone (Black) 95% CI - High,% Drive Alone (Hispanic),% Drive Alone (Hispanic) 95% CI - Low,% Drive Alone (Hispanic) 95% CI - High,% Drive Alone (White),% Drive Alone (White) 95% CI - Low,% Drive Alone (White) 95% CI - High,# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low,95% CI - High,Z-Score
1,36000,New York,NaN,191428,5456,5420,5493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.61,15.69,17.57,NaN,3.506,3.323,3.689,NaN,3.942,3.724,4.16,NaN,NaN,7.947,7.905,7.988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.09,13.21,15.03,NaN,25.5,NaN,NaN,NaN,9.1,NaN,24.7,NaN,NaN,NaN,93.19,NaN,18.81,17.82,19.85,NaN,1078,5167,20.86,20.18,21.55,NaN,116814,588.5,NaN,15.13,15,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1079651,6.634,6.515,6.753,NaN,16288,82.06,1219:1,NaN,16052,82.14,1217:1,NaN,56523,289.2,346:1,NaN,4203,NaN,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,NaN,NaN,NaN,NaN,48,NaN,NaN,NaN,NaN,NaN,NaN,207863,81.8,NaN,3619298,5306912,68.2,67.91,68.49,NaN,393647,9574705,4.111,NaN,18.8,18.2,19.4,NaN,NaN,NaN,NaN,NaN,NaN,138256,24105,5.736,NaN,1392265,4089733,34.04,33.71,34.37,NaN,15830,7.975,NaN,7.484e+04,379,NaN,48206,48.85,48.42,49.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,23.86,23.73,23.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.14,53.04,53.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9246571,38.1,37.86,38.34,NaN
2,36001,New York,Albany,3307,5821,5512,6130,-0.6156,NaN,NaN,NaN,2101,1538,2803,9758,8696,1.082e+04,5396,4202,6590,5495,5139,5851,14.21,13.8,14.64,-0.3939,3.331,3.203,3.46,-0.9202,4.274,4.126,4.429,0.6967,NaN,8.118,7.752,8.485,1.071,NaN,NaN,NaN,7.898,6.8,9,12.53,11.5,13.5,8.88,7.5,10.2,6.682,6.3,7.1,14.53,14.06,15.03,-0.5216,27.3,24.6,30,-0.7114,8,0.5744,22,19.7,24.2,-0.9085,92.06,-0.8691,20.02,19.33,20.71,-0.0003507,27,105,25.71,20.72,30.91,0.4303,1877,606.2,1.227,10.9,10.2,11.6,-0.8864,NaN,NaN,NaN,4.308,2.8,6.3,28.15,25.4,30.9,24.56,20.8,28.3,5.587,5,6.2,10808,4.401,3.805,4.997,-1.047,311,100.4,996:1,-1.344,282,91.82,1089:1,-1.268,1094,356.2,281:1,-1.21,4274,-0.2849,NaN,1729,8061,5537,3795,46,0.01229,NaN,43,39,30,47,52,-0.7166,46,54,36,46,54,3014,84.41,0.09237,57470,74847,76.78,74.43,79.14,-1.778,5844,158835,3.679,-1.167,15.3,11.96,18.64,-0.5029,10.23,8.056,36.4,40.16,7.949,128331,26572,4.83,0.2051,21275,56350,37.76,35.26,40.25,0.5762,455,14.7,-1.341,1074,348.2,0.9027,715,46.33,42.94,49.73,-1.182,NaN,NaN,NaN,17.33,10.27,27.39,41.46,33.16,51.2,28.56,18.65,41.84,51.06,46.91,55.21,9.1,0.494,Yes,0.9919,15.55,14.64,16.46,14.68,13.79,15.57,0.8903,0.6877,1.093,0.6728,0.4645,0.8811,-0.2133,75.79,74.9,76.68,0.0729,NaN,NaN,NaN,64.13,59.5,68.76,57.87,54.24,61.49,60.07,53.88,66.26,84.15,83.45,84.85,156817,21.1,19.97,22.23,-1.2
3,36003,New York,Allegany,628,7283,6363,8203,0.7653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.42,13.74,15.11,-0.2976,3.72,3.517,3.908,0.398,4.307,4.084,4.533,0.8437,NaN,6.958,6.092,7.823,-0.3078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.56,15.82,17.32,0.7314,35.9,32.1,40,0.9775,8.1,0.3612,29.3,25.6,33.3,1.13,62.36,1.121,20.05,19.01,21.1,0.02385,5,17,29.41,16.39,42.87,0.8291,92,196.2,-0.8635,14.43,12.5,16.4,-0.3654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,5.854,4.901,6.807,0.2104,20,42.65,2345:1,0.6134,15,32.31,3095:1,0.8504,103,221.8,451:1,-0.05789,5268,1.014,NaN,NaN,NaN,NaN,NaN,50,-0.75,NaN,NaN,NaN,NaN,NaN,47,0.6805,NaN,NaN,25,NaN,47,502,87.85,-0.5657,5774,9409,61.37,57.59,65.14,0.1692,1096,19461,5.632,1.623,22.8,16.49,29.11,0.9231,NaN,NaN,NaN,38.19,26.25,85765,20579,4.168,-0.5762,3177,9385,33.85,29.4,38.31,0.03517,74,15.78,-1.683,91.5,195,-0.2138,128,54.33,44.92,63.74,-0.4532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.5,-0.1268,Yes,0.9919,14.14,12.59,15.69,10.54,9.161,11.92,2.108,1.445,2.771,2.496,1.875,3.117,-0.4647,75.65,74.09,77.21,0.06375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,6.968,38.97,75.52,74.39,76.65,19556,29.3,27.42,31.18,-0.4678
4,36005,New York,Bronx,15016,6696,6554,6838,0.2105,NaN,NaN,NaN,3200,2626,3774,8274,7980,8569,5515,5345,5684,8224,7648,8800,26.8,26.24,27.33,5.447,4.66,4.533,4.785,3.587,4.088,3.964,4.212,-0.13,NaN,9.452,9.303,9.601,2.655,13.27,6.5,20,10.62,9.9,11.3,11.56,11.3,11.9,8.493,8.3,8.7,7.525,7,8,15.92,15.52,16.31,0.3371,29,26.4,31.8,-0.3776,7.7,1.214,31.3,28.8,33.8,1.689,100,-1.401,15.95,15.5,16.37,-2.682,31,200,15.5,12.16,19.15,-0.6713,17711,1204,4.274,26.25,25.7,26.8,1.382,NaN,NaN,NaN,6.775,5.3,8.5,21.71,20.8,22.6,31.17,30.4,31.9,10.16,8.9,11.4,110580,8.903,8.188,9.618,2.85,832,56.55,1768:1,0.1424,729,50.9,1965:1,0.1885,2945,205.6,486:1,0.081,5421,1.214,1644,3464,6050,6078,4377,33,2.49,23,29,33,33,36,38,3.195,26,51,33,35,45,14750,67.51,3.322,209243,408923,51.17,50.18,52.16,1.457,34319,605864,5.664,1.669,37.6,34.5,40.7,3.737,47.72,32.45,37.84,44.63,18.7,85934,12920,6.651,2.355,213053,354082,60.17,58.87,61.47,3.683,386,2.624,2.471,8486,586.1,2.636,3306,45.58,44.03,47.14,-1.25,NaN,NaN,NaN,16.5,12.21,21.81,48.58,45.65,51.5,39.19,37.26,41.12,76.62,70.17,83.06,10.3,1.736,No,-0.9919,38.92,38.33,39.52,30.86,30.28,31.43,12.23,11.84,12.62,0.8579,0.7391,0.9767,3.961,23.38,22.88,23.88,-3.256,24.69,14.6,34.79,42.4,40.08,44.73,34.72,33.68,35.75,28.26,27.26,29.26,59.03,57.32,60.74,578100,52.9,51.21,54.59,1.641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,821,6950,6141,7758,0.4503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.26,13.7,14.81,-0.3707,3.766,3.576,3.934,0.5569,4.114,3.896,4.302,-0.01293,NaN,7.396,6.591,8.202,0.2132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.35,14.74,15.95,-0.01288,33.6,30,37.2,0.5258,8.4,-0.2786,25.8,22.9,28.9,0.1527,66.04,0.8746,19.56,18.74,20.34,-0.2994,5,36,13.89,6.439,23.41,-0.8451,159,258,-0.5485,24.51,21.6,27.4,1.125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2629,5.548,4.714,6.382,-0.05454,20,32.46,3081:1,0.9586,14,22.88,4371:1,1.186,86,140.5,712:1,0.6391,4576,0.1097,NaN,NaN,NaN,NaN,NaN,43,0.584,NaN,NaN,NaN,64,43,46,0.96,NaN,NaN,23,45,46,690,79.57,1.018,8129,14767,55.05,50.63,59.47,0.9672,1165,28164,4.136,-0.5139,16,10.88,21.12,-0.3698,NaN,NaN,NaN,40.11,15.39,100270,24141,4.154,-0.5928,4050,11574,34.99,29.55,40.44,0.1932,59,9.575,0.2761,88,141.1,-0.607,182,58.86,50.31,67.41,-0.04074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.9,0.2871,Yes,0.9919,14.92,13.13,16.71,13.19,11.46,14.91,1.623,0.9822,2.264,0.666,0.3735,0.9585,-0.3256,81.42,79.29,83.55,0.4304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27834,39.1,36.29,41.91,0.4078
60,36117,New York,Wayne,1221,7147,6477,7817,0.6366,NaN,NaN,NaN,NaN,NaN,NaN,1.517e+04,1.044e+04,2.131e+04,NaN,NaN,NaN,7019,6313,7725,15.45,14.86,16.11,0.1804,3.56,3.376,3.739,-0.1418,4.041,3.839,4.245,-0.3378,NaN,7.108,6.497,7.719,-0.1292,NaN,NaN,NaN,NaN,NaN,NaN,8.368,4.9,11.9,8.424,5.6,11.3,7.005,6.4,7.6,16.09,15.46,16.82,0.443,36.3,32.5,40.2,1.056,8.6,-0.7052,29.4,26.1,32.8,1.158,61.89,1.153,20.68,19.76,21.66,0.4373,10,57,17.54,11.11,24.9,-0.4509,263,290.1,-0.3848,18.98,17,20.9,0.3071,NaN,NaN,NaN,NaN,NaN,NaN,34.25,23.1,48.9,33.59,23.9,45.9,17.44,15.5,19.4,3530,4.781,4.066,5.496,-0.7182,26,28.68,3487:1,1.087,44,48.85,2047:1,0.2614,94,104.4,958:1,0.9491,5625,1.48,NaN,NaN,4428,5049,5587,45,0.2029,NaN,NaN,35,29,46,51,-0.4372,NaN,NaN,51,47,51,1164,87.2,-0.4416,12878,20010,64.36,60.59,68.12,-0.2085,1823,43877,4.155,-0.4877,14.6,10.31,18.89,-0.636,NaN,NaN,42.36,32.44,13.27,103229,26694,3.867,-0.9308,6378,19324,33.01,29.01,37,-0.08214,98,10.81,-0.1134,163,178.4,-0.3347,294,64.61,57.23,72,0.4833,NaN,NaN,NaN,NaN,NaN,NaN,69.16,34.52,123.7,NaN,NaN,NaN,65.91,58.09,73.72,8.6,-0.02337,Yes,0.9919,12.14,10.75,13.53,10.6,9.24,11.96,1.517,1.025,2.01,0.7109,0.4287,0.993,-0.8225,84.48,83.13,85.82,0.6243,NaN,NaN,NaN,NaN,NaN,NaN,66.62,54.63,78.61,62.02,47.33,76.7,83.67,82.04,85.3,42850,39.3,37.01,41.59,0.4257
61,36119,New York,Westchester,7306,4258,4105,4410,-2.092,NaN,NaN,NaN,2191,1726,2657,6672,6193,7151,3310,3060,3560,4155,3936,4375,14.8,14.52,15.09,-0.119,3.151,3.062,3.238,-1.528,3.911,3.801,4.018,-0.9146,NaN,7.954,7.757,8.15,0.8749,NaN,NaN,NaN,8.743,8,9.5,12.16,11.6,12.8,7.139,6.8,7.5,6.879,6.6,7.2,11.37,11.11,11.66,-2.475,20.7,18.8,22.7,-2.008,9.1,-1.771,21.2,19.4,23.3,-1.132,99.62,-1.376,18.01,17.59,18.46,-1.322,38,175,21.71,17.92,25.7,-0.00107,3812,388.9,0.1188,8.952,8.6,9.3,-1.175,NaN,NaN,NaN,1.441,0.9,2.2,14.54,13.3,15.8,22.52,21.3,23.7,1.339,1.1,1.5,55634,6.929,6.334,7.525,1.141,1346,137.3,728:1,-2.593,1066,110.2,908:1,-1.921,3745,387,258:1,-1.474,3870,-0.8128,NaN,2212,6344,4257,3447,46,0.01229,NaN,36,40,43,48,51,-0.4372,40,51,36,41,54,11163,89.55,-0.8919,168381,234209,71.89,70.58,73.21,-1.16,18828,484256,3.888,-0.8689,10.3,8.036,12.56,-1.454,18.86,9.733,18.83,20.3,3.508,205341,33198,6.185,1.805,54485,214300,25.42,24.09,26.75,-1.133,821,8.375,0.6549,2148,220.6,-0.0274,1995,40.95,39.16,42.75,-1.672,NaN,NaN,NaN,16.41,12.26,21.52,41.06,36.28,45.83,24.51,21.7,27.32,50.81,48.1,53.52,10.4,1.839,Yes,0.9919,24.24,23.62,24.85,20.9,20.3,21.49,4.26,3.968,4.553,0.7344,0.6186,0.8502,1.338,57.59,57.04,58.13,-1.083,49.6,40.99,58.21,64.81,62.53,67.1,56.33,54.49,58.17,55.5,54.25,56.74,78.44,77.77,79.11,468771,41.2,40.18,42.22,0.5954
62,36121,New York,Wyoming,500,6456,5533,7379,-0.01592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.95,13.36,14.52,-0.512,3.437,3.257,3.609,-0.5591,4.026,3.82,4.23,-0.404,NaN,6.376,5.434,7.317,-0.9993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.9,15.23,16.53,0.3227,37.9,33.5,42.3,1.37,8.2,0.1479,26.5,22.6,30.5,0.3482,69,0.6763,21.27,20.43,22.13,0.828,3,23,13.04,4.243,25.4,-0.9362,73,180.3,-0.9446,13.11,10.6,15.7,-0.5607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1366,4.533,3.818,5.248,-0.9328,15,37.04,2700:1,0.8032,18,44.9,2227:1,0.402,86,214.5,466:1,0.004645,5306,1.064,NaN,NaN,NaN,NaN,NaN,43,0.584,NaN,NaN,NaN,NaN,NaN,51,-0.4372,NaN,NaN,NaN,NaN,NaN,339,93.81,-1.704,5675,10283,55.19,51.28,59.1,0.9495,838,18093,4.632,0.1936,12.2,8.03,16.37,-1.092,NaN,NaN,NaN,52.78,14.18,98805,25474,3.879,-0.9172,2449,7972,30.72,26,35.44,-0.3989,61,15.06,-1.457,45.5,111,-0.8263,136,66.81,55.58,78.04,0.6834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8,0.1836,Yes,0.9919,9.189,7.688,10.69,8.019,6.641,9.397,1.077,0.4961,1.659,0.2535,0.05665,0.4503,-1.349,83.28,81.21,85.35,0.5482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18120,37.5,34.2,40.8,0.2649

In [ ]:
#Deleting columns
to_remove=df7.iloc[:,np.r_[1:4,5:23,24:59,60:63,64:141,143:146,147:240]]
df7c=df7.drop(columns=to_remove)

#Deleting rows
df7c=df7c.drop([0,1])

#Renaming columns
new_col7= {'Unnamed: 0':'fips',
          'Unnamed: 4':'yppl',
          'Poor or fair health':'%poor_fair_health',
          'Adult obesity':'%adult_obesity',
          'Food environment index':'food_environment_index',
          'High school graduation': 'graduation_cohort',
          'Unnamed: 142': 'graduation_rate',
          'Unnamed: 146':'%some_college'}

df7c=df7c.rename(columns=new_col7)
df7c

,fips,yppl,%poor_fair_health,%adult_obesity,food_environment_index,graduation_cohort,graduation_rate,%some_college
2,36001,5821,14.21,27.3,8,3014,84.41,76.78
3,36003,7283,14.42,35.9,8.1,502,87.85,61.37
4,36005,6696,26.8,29,7.7,14750,67.51,51.17
5,36007,7415,15.93,28,8,2205,82.95,67.26
6,36009,7255,16.37,37.6,8.1,1041,85.01,56.04
...,...,...,...,...,...,...,...,...
59,36115,6950,14.26,33.6,8.4,690,79.57,55.05
60,36117,7147,15.45,36.3,8.6,1164,87.2,64.36
61,36119,4258,14.8,20.7,9.1,11163,89.55,71.89
62,36121,6456,13.95,37.9,8.2,339,93.81,55.19
63,36123,7491,14.67,29.5,8.8,214,78.5,50.89

### 4th Sheet: Additional Measure Data

In [ ]:
df8=pd.read_excel('2020_health_r.xlsx',sheet_name='Additional Measure Data')
df8

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Life expectancy,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Premature age-adjusted mortality,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Child mortality,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Infant mortality,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Frequent physical distress,Unnamed: 79,Unnamed: 80,Frequent mental distress,Unnamed: 82,Unnamed: 83,Diabetes prevalence,Unnamed: 85,Unnamed: 86,HIV prevalence,Unnamed: 88,Food insecurity,Unnamed: 90,Limited access to healthy foods,Unnamed: 92,Drug overdose deaths,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Motor vehicle crash deaths,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Insufficient sleep,Unnamed: 132,Unnamed: 133,Uninsured adults,Unnamed: 135,Unnamed: 136,Unnamed: 137,Uninsured children,Unnamed: 139,Unnamed: 140,Unnamed: 141,Other primary care providers,Unnamed: 143,Disconnected youth,Unnamed: 145,Unnamed: 146,Reading scores,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Math scores,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156,Median household income,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Children eligible for free or reduced price lunch,Residential segregation - Black/White,Residential segregation - non-White/White,Homicides,Unnamed: 179,Unnamed: 180,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Suicides,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Firearm fatalities,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Juvenile arrests,Unnamed: 236,Unnamed: 237,Unnamed: 238,Traffic volume,Homeownership,Unnamed: 241,Unnamed: 242,Unnamed: 243,Severe housing cost burden,Unnamed: 245,Unnamed: 246,Unnamed: 247,Demographics,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255,Unnamed: 256,Unnamed: 257,Unnamed: 258,Unnamed: 259,Unnamed: 260,Unnamed: 261,Unnamed: 262,Unnamed: 263,Unnamed: 264,Unnamed: 265,Unnamed: 266,Unnamed: 267,Unnamed: 268,Unnamed: 269
0,FIPS,State,County,Life Expectancy,95% CI - Low,95% CI - High,Life Expectancy (AIAN),Life Expectancy (AIAN) 95% CI - Low,Life Expectancy (AIAN) 95% CI - High,Life Expectancy (Asian),Life Expectancy (Asian) 95% CI - Low,Life Expectancy (Asian) 95% CI - High,Life Expectancy (Black),Life Expectancy (Black) 95% CI - Low,Life Expectancy (Black) 95% CI - High,Life Expectancy (Hispanic),Life Expectancy (Hispanic) 95% CI - Low,Life Expectancy (Hispanic) 95% CI - High,Life Expectancy (White),Life Expectancy (White) 95% CI - Low,Life Expectancy (White) 95% CI - High,# Deaths,Age-Adjusted Death Rate,95% CI - Low,95% CI - High,Age-Adjusted Mortality (AIAN),Age-Adjusted Mortality (AIAN) 95% CI - Low,Age-Adjusted Mortality (AIAN) 95% CI - High,Age-Adjusted Mortality (Asian),Age-Adjusted Mortality (Asian) 95% CI - Low,Age-Adjusted Mortality (Asian) 95% CI - High,Age-Adjusted Mortality (Black),Age-Adjusted Mortality (Black) 95% CI - Low,Age-Adjusted Mortality (Black) 95% CI - High,Age-Adjusted Mortality (Hispanic),Age-Adjusted Mortality (Hispanic) 95% CI - Low,Age-Adjusted Mortality (Hispanic) 95% CI - High,Age-Adjusted Mortality (White),Age-Adjusted Mortality (White) 95% CI - Low,Age-Adjusted Mortality (White) 95% CI - High,# Deaths,Child Mortality Rate,95% CI - Low,95% CI - High,Child Mortality Rate (AIAN),Child Mortality Rate (AIAN) 95% CI - Low,Child Mortality Rate (AIAN) 95% CI - High,Child Mortality Rate (Asian),Child Mortality Rate (Asian) 95% CI - Low,Child Mortality Rate (Asian) 95% CI - High,Child Mortality Rate (Black),Child Mortality Rate (Black) 95% CI - Low,Child Mortality Rate (Black) 95% CI - High,Child Mortality Rate (Hispanic),Child Mortality Rate (Hispanic) 95% CI - Low,Child Mortality Rate (Hispanic) 95% CI - High,Child Mortality Rate (White),Child Mortality Rate (White) 95% CI - Low,Child Mortality Rate (White) 95% CI - High,# Deaths,Infant Mortality Rate,95% CI - Low,95% CI - High,Infant Mortality Rate (AIAN),Infant Mortality Rate (AIAN) 95% CI - Low,Infant Mortality Rate (AIAN) 95% CI - High,Infant Mortality Rate (Asian),Infant Mortality Rate (Asian) 95% CI - Low,Infant Mortality Rate (Asian) 95% CI - High,Infant Mortality Rate (Black),Infant Mortality Rate (Black) 95% CI - Low,Infant Mortality Rate (Black) 95% CI - High,Infant Mortality Rate (Hispanic),Infant Mortality Rate (Hispanic) 95% CI - Low,Infant Mortality Rate (Hispanic) 95% CI - High,Infant Mortality Rate (White),Infant Mortality Rate (White) 95% CI - Low,Infant Mortality Rate (White) 95% CI - High,% Frequent Physical Distress,95% CI - Low,95% CI - High,% Frequent Mental Distress,95% CI - Low,95% CI - High,% Adults with Diabetes,95% CI - Low,95% CI - High,# HIV Cases,HIV Prevalence Rate,# Food Insecure,% Food Insecure,# Limited Access,% Limited Access to Healthy Foods,# Drug Overdose Deaths,Drug Overdose Mortality Rate,95% CI - Low,95% CI - High,Drug Overdose Mortality Rate (AIAN),Drug Overdose Mortality Rate (AIAN) 95% CI - Low,Drug Overdose Mortality Rate (AIAN) 95% CI - High,Drug Overdose Mortality Rate (Asian),Drug Overdose Mortality Rate (Asian) 95% CI - Low,Drug Overdose Mortality Rate (Asian) 95% CI - ...,Drug Overdose Mortality Rate (Black),Drug Overdose Mortality Rate (Black) 95% CI - Low,Drug Overdose Mortality Rate (Black) 95% CI - ...,Drug Overdose Mortality Rate (Hispanic),Drug Overdose Mortality Rate (Hispanic) 95% CI...,Drug Overdose Mortality Rate (Hispanic) 95% CI...,Drug Overdose Mortality Rate (White),Drug Overdose Mortality Rate (White) 95% CI - Low,Drug Overdose Mortality Rate (White) 95% CI - ...,# Motor Vehicle Deaths,Motor Vehicle Mortality Rate,95% CI - Low,95% CI - High,MV Mortality Rate (AIAN),MV Mortality Rate (AIAN) 95% CI - Low,MV Mortality Rate (AIAN) 95% CI - High,MV Mortality Rate (Asian),MV Mortality Rate (Asian) 95% CI - Low,MV Mortality Rate (Asian) 95% CI - High,MV Mortality Rate (Black),MV Mortality Rate (Black) 95% CI - Low,MV Mortality Rate (Black) 95% CI - High,MV Mortality Rate (Hispanic),MV Mortality Rate (Hispanic) 95% CI - Low,MV Mortality Rate (Hispanic) 95% CI - High,MV Mortality Rate (White),MV Mortality Rate (White) 95% CI - Low,MV Mortality Rate (White) 95% CI - High,% Insufficient Sleep,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Other Primary Care Provider Rate,Other Primary Care Provider Ratio,% Disconnected Youth,95% CI - Low,95% CI - High,Average Grade Performance,Average Grade Performance (Asian),Average Grade Performance (Black),Average Grade Performance (Hispanic),Average Grade Performance (White),Average Grade Performance,Average Grade Performance (Asian),Average Grade Performance (Black),Average Grade Performance (Hispanic),Average Grade Performance (White),Median Household Income,95% CI - Low,95% CI - High,Household Income (AIAN),Household Income (AIAN) 95% CI - Low,Household Income (AIAN) 95% CI - High,Household Income (Asian),Household Income (Asian) 95% CI - Low,Household Income (Asian) 95% CI - High,Household Income (Black),Household Income (Black) 95% CI - Low,Household Income (Black) 95% CI - High,Household Income (Hispanic),Household Income (Hispanic) 95% CI - Low,Household Income (Hispanic) 95% CI - High,Household Income (White),Household Income (White) 95% CI - Low,Household Income (White) 95% CI - High,% Enrolled in Free or Reduced Lunch,Segregation index,Segregation Index,Homicide Rate,95% CI - Low,95% CI - High,Homicide Rate (AIAN),Homicide Rate (AIAN) 95% CI - Low,Homicide Rate (AIAN) 95% CI - High,Homicide Rate (Asian),Homicide Rate (Asian) 95% CI - Low,Homicide Rate (Asian) 95% CI - High,Homicide Rate (Black),Homicide Rate (Black) 95% CI - Low,Homicide Rate (Black) 95% CI - High,Homicide Rate (Hispanic),Homicide Rate (Hispanic) 95% CI - Low,Homicide Rate (Hispanic) 95% CI - High,Homicide Rate (White),Homicide Rate (White) 95% CI - Low,Homicide Rate (White) 95% CI - High,# Deaths,Suicide Rate (Age-Adjusted),95% CI - Low,95% CI - High,Crude Rate,Suicide Rate (AIAN),Suicide Rate (AIAN) 95% CI - Low,Suicide Rate (AIAN) 95% CI - High,Suicide Rate (Asian),Suicide Rate (Asian) 95% CI - Low,Suicide Rate (Asian) 95% CI - High,Suicide Rate (Black),Suicide Rate (Black) 95% CI - Low,Suicide Rate (Black) 95% CI - High,Suicide Rate (Hispanic),Suicide Rate (Hispanic) 95% CI - Low,Suicide Rate (Hispanic) 95% CI - High,Suicide Rate (White),Suicide Rate (White) 95% CI - Low,Suicide Rate (White) 95% CI - High,# Firearm Fatalities,Firearm Fatalities Rate,95% CI - Low,95% CI - High,Firearm Fatalities Rate (AIAN),Firearm Fatalities Rate (AIAN) 95% CI - Low,Firearm Fatalities Rate (AIAN) 95% CI - High,Firearm Fatalities Rate (Asian),Firearm Fatalities Rate (Asian) 95% CI - Low,Firearm Fatalities Rate (Asian) 95% CI - High,Firearm Fatalities Rate (Black),Firearm Fatalities Rate (Black) 95% CI - Low,Firearm Fatalities Rate (Black) 95% CI - High,Firearm Fatalities Rate (Hispanic),Firearm Fatalities Rate (Hispanic) 95% CI - Low,Firearm Fatalities Rate (Hispanic) 95% CI - High,Firearm Fatalities Rate (White),Firearm Fatalities Rate (White) 95% CI - Low,Firearm Fatalities Rate (White) 95% CI - High,Non-Petitioned Cases,Petitioned Cases,Denominator,Juvenile Arrest Rate,Average Traffic Volume per Meter of Major Road...,# Homeowners,% Homeowners,95% CI - Low,95% CI - High,# Households with Severe Cost Burden,% Severe Housing Cost Burden,95% CI - Low,95% CI - High,Population,% less than 18 years of age,% 65 and over,# Black,% Black,# American Indian & Alaska Native,% American Indian & Alaska Native,# Asian,% Asian,# Native Hawaiian/Other Pacific Islander,% Native Hawaiian/Other Pacific Islander,# Hispanic,% Hispanic,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural
1,36000,New York,NaN,81.27,81.23,81.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191428,278.8,277.5,280.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6485,39.03,38.08,39.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7642,4.63,4.526,4.733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.22,9.512,10.98,11.83,10.98,12.75,9.8,NaN,NaN,127934,759.7,2261250,11.4,4.435e+05,2.289,11256,19.03,18.68,19.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8035,5.827,5.699,5.954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.71,35.63,37.8,976624,8.009,7.771,8.247,113299,2.636,2.398,2.874,118.1,847:1,6.295,6.085,6.505,3.113,NaN,NaN,NaN,NaN,2.859,NaN,NaN,NaN,NaN,67648,6.69e+04,6.84e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.91,73.92,61.38,3.279,3.184,3.375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8433,8.083,7.907,8.259,8.546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4217,4.273,4.144,4.402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3543,4514,1372600,5.87,2359,3943356,53.9,53.6,54.19,1425795,20.11,19.98,20.23,19542209,20.82,16.44,2833908,14.5,190414,0.9744,1750013,8.955,26745,0.1369,3754130,19.21,10830524,55.42,1302270,7.057,6.989,7.124,51.45,2349997,12.13
2,36001,New York,Albany,80.03,79.72,80.35,NaN,NaN,NaN,90.62,86.46,94.78,77.1,75.8,78.41,85.58,81.98,89.17,80.3,79.96,80.65,3307,304.1,293.4,314.9,NaN,NaN,NaN,135.3,102.7,174.9,505.2,463.2,547.3,264,210.7,317.2,288.7,276.8,300.6,99,43.06,35,52.42,NaN,NaN,NaN,NaN,NaN,NaN,76.5,52.98,106.9,NaN,NaN,NaN,35.66,26.55,46.89,132,6.233,5.169,7.296,NaN,NaN,NaN,NaN,NaN,NaN,16.74,12.8,21.5,NaN,NaN,NaN,3.99,3.005,5.193,9.953,9.689,10.23,12.21,11.92,12.5,9.1,7.8,10.5,1104,411.3,36970,12,1.454e+04,4.78,133,14.37,11.93,16.81,NaN,NaN,NaN,NaN,NaN,NaN,16.76,10.38,25.62,NaN,NaN,NaN,14.89,11.99,17.8,111,5.15,4.192,6.108,NaN,NaN,NaN,NaN,NaN,NaN,3.835,1.914,6.862,NaN,NaN,NaN,5.555,4.461,6.836,33.83,33.24,34.43,9660,5.118,4.284,5.952,1292,2.146,1.55,2.741,190.2,526:1,4.786,2.942,6.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64536,5.987e+04,6.92e+04,46902,2.602e+04,6.778e+04,81778,7.329e+04,9.027e+04,32005,3.066e+04,3.335e+04,38522,3.292e+04,4.412e+04,73077,7.165e+04,7.451e+04,35.5,60.42,44.63,2.969,2.287,3.791,NaN,NaN,NaN,NaN,NaN,NaN,13.6,9.669,18.59,NaN,NaN,NaN,1.186,0.714,1.852,150,9.236,7.71,10.76,9.721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74,4.795,3.765,6.02,NaN,NaN,NaN,NaN,NaN,NaN,9.641,5.889,14.89,NaN,NaN,NaN,4.394,3.261,5.793,125,158,19200,14.74,2107,71253,56.55,55.65,57.44,18267,14.78,13.84,15.72,307117,18.35,16.96,39292,12.79,911,0.2966,20834,6.784,207,0.0674,18737,6.101,220533,71.81,5552,1.902,1.614,2.191,51.57,29496,9.696
3,36003,New York,Allegany,78,77.19,78.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628,366.6,335.9,397.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,39.25,21.97,64.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,6.263,3.877,9.574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.12,10.71,11.53,13.21,12.81,13.62,10.9,8.7,13.5,32,79.2,5880,12.4,1464,2.992,16,11.4,6.514,18.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,8.131,5.358,11.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.84,34.98,36.7,1718,6.908,5.717,8.1,305,3.101,2.029,4.174,77.54,1290:1,5.933,3.771,8.094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46262,4.278e+04,4.975e+04,34239,1.069e+04,5.779e+04,NaN,NaN,NaN,41406,3.555e+04,4.726e+04,19141,6465,3.182e+04,47271,4.561e+04,4.894e+04,51.94,NaN,35.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,15.24,10.43,21.52,15.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,13.16,8.94,18.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,18,3300,9.697,27.25,13533,75.15,74.54,75.75,1824,10.53,9.233,11.82,46430,20.22,18.99,593,1.277,147,0.3166,601,1.294,19,0.04092,779,1.678,43781,94.29,206,0.4619,0.2184,0.7054,49.24,38540,78.74
4,36005,New York,Bronx,80.56,80.37,80.74,142.3,84.42,200.2,91.2,89.04,93.36,79.03,78.67,79.38,83.03,82.71,83.35,78.46,77.95,78.96,15016,346.1,340.5,351.7,NaN,NaN,NaN,148.5,130.8,166.2,412.2,401.3,423,288.6,281.5,295.8,404.8,386.2,423.4,623,42.74,39.39,46.1,NaN,NaN,NaN,48.25,31.23,71.23,60.42,52.94,67.89,29.27,25.72,32.82,56.8,42.55,74.3,750,4.971,4.616,5.327,NaN,NaN,NaN,4.936,3.129,7.406,6.989,6.198,7.78,3.27,2.903,3.638,5.068,3.762,6.682,15.13,14.81,15.46,13.76,13.47,14.04,12.5,10.9,14.1,26829,2236,233450,16,12.74,0.0009199,1087,24.94,23.45,26.42,NaN,NaN,NaN,NaN,NaN,NaN,24.49,21.81,27.17,23.6,21.68,25.53,38.62,32.6,44.64,378,3.75,3.372,4.128,NaN,NaN,NaN,NaN,NaN,NaN,3.022,2.436,3.706,3.513,3.021,4.005,7.389,5.812,9.262,39.9,39.34,40.48,102373,11.44,10.48,12.39,8971,2.452,1.856,3.048,114.4,874:1,9.393,8.467,10.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38566,3.649e+04,4.064e+04,30884,2.277e+04,3.899e+04,52028,4.924e+04,5.482e+04,40681,3.988e+04,4.148e+04,32257,3.149e+04,3.303e+04,62230,5.955e+04,6.491e+04,86.6,46.54,39.47,6.637,6.134,7.14,NaN,NaN,NaN,NaN,NaN,NaN,11.76,10.54,12.98,4.822,4.245,5.398,2.561,1.673,3.753,396,5.458,4.913,6.003,5.46,NaN,NaN,NaN,5.483,3.069,9.043,5.016,4.068,5.965,4.487,3.815,5.158,11.2,8.762,14.1,319,4.398,3.916,4.881,NaN,NaN,NaN,NaN,NaN,NaN,7.974,6.789,9.159,2.995,2.462,3.529,2.822,1.724,4.358,286,486,116600,6.621,3706,97983,19.61,19.17,20.04,151717,31.66,30.97,32.36,1432132,24.77,12.8,418506,29.22,41726,2.914,64447,4.5,5940,0.4148,807228,56.37,130764,9.131,210911,15.84,15.5,16.18,52.87,39,0.002816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,78.57,77.85,79.28,NaN,NaN,NaN,NaN,NaN,NaN,77.33,69.27,85.38,90.58,68.74,112.4,78.43,77.69,79.16,821,340.5,315.8,365.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,46.48,29.13,70.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,5.175,3.203,7.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.04,10.67,11.4,12.32,11.96,12.68,12.4,10.4,14.7,189,353.5,6520,10.5,2710,4.286,14,7.583,4.146,12.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,12.18,9.121,15.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.1,35.35,36.86,2342,6.543,5.47,7.615,314,2.569,1.735,3.403,55.56,1800:1,12.74,5.744,19.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55913,5.108e+04,6.074e+04,NaN,NaN,NaN,83224,6.553e+04,1.009e+05,NaN,NaN,NaN,42679,1.891e+04,6.645e+04,54032,5.103e+04,5.703e+04,46.45,65.75,29.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,11.28,7.762,15.84,11.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,8.085,5.232,11.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,19,4200,11.9,160,17507,72.92,71.62,74.21,3122,13.37,11.5,15.23,61197,18.73,19.48,1799,2.94,201,0.3284,342,0.5589,21,0.03432,1744,2.85,56483,92.3,390,0.6622,0.2426,1.082,48.24,42923,67.9

In [ ]:
#Remove columns
to_remove=df8.iloc[:,np.r_[1:3,4:84,85:90,91,93:157,158:175,176:252,253,255,257,259,261,263:270]]
df8c=df8.drop(columns=to_remove)

#Remove rows
df8c=df8c.drop([0,1])

#Rename columns
new_col8={'Unnamed: 0': 'fips',
          'Life expectancy':'life_expectancy',
          'Diabetes prevalence':'%diabetes',
          'Unnamed: 90':'%food_insecure',
          'Unnamed: 92':'%limited_access',
          'Median household income':'household_income',
          'Children eligible for free or reduced price lunch':'%lunch_aid',
          'Unnamed: 252':'%african_american',
          'Unnamed: 254':'%american_indian',
          'Unnamed: 256':'%asian',
          'Unnamed: 258':'%pacific_islander',
          'Unnamed: 260':'%hispanic',
          'Unnamed: 262':'%white'
    
}
df8c=df8c.rename(columns=new_col8)
df8c

,fips,life_expectancy,%diabetes,%food_insecure,%limited_access,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
2,36001,80.03,9.1,12,4.78,64536,35.5,12.79,0.2966,6.784,0.0674,6.101,71.81
3,36003,78,10.9,12.4,2.992,46262,51.94,1.277,0.3166,1.294,0.04092,1.678,94.29
4,36005,80.56,12.5,16,0.0009199,38566,86.6,29.22,2.914,4.5,0.4148,56.37,9.131
5,36007,78.67,10.6,12.8,3.241,50928,54.4,5.47,0.2682,4.427,0.06679,4.342,83
6,36009,77.85,13.3,12.5,2.584,48017,50.84,1.378,3.548,0.8719,0.03774,2.124,90.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,78.57,12.4,10.5,4.286,55913,46.45,2.94,0.3284,0.5589,0.03432,2.85,92.3
60,36117,78.69,12.1,9.8,3.489,61118,46.74,2.802,0.4164,0.6962,0.04108,4.473,89.83
61,36119,83.51,7.6,7.7,1.379,94521,36.18,13.8,0.9565,6.436,0.1323,25.14,53.09
62,36121,78.74,12.3,10.5,6.067,57709,43.36,5.119,0.4441,0.5638,0.02994,3.261,89.9
63,36123,78.21,14.3,9.9,0.5,51089,56.99,0.8856,0.3301,0.8252,0.02013,2.311,94.73

### Merge 4 sheets

In [ ]:
#Merge first 2
merged_df3=pd.merge(df5c,df6c,on='fips',how='outer')

#Merge second 2
merged_df4=pd.merge(df7c,df8c,on='fips',how='outer')

#Merge all together
rank2020=pd.merge(merged_df3,merged_df4,on='fips',how='outer')


#Keep only counties in NYC
county_nyc=['New York','Kings','Bronx','Richmond','Queens']
#rank2020=rank2020[rank2020['county_name'].isin(county_nyc)]
rank2020=rank2020.reset_index().drop(columns=['index','health_outcomes_z','health_factors_z','lenght_life_z','quality_life_z'])
rank2020

,fips,state,county_name,health_outcomes_r,health_factors_r,length_life_r,quality_life_r,yppl,%poor_fair_health,%adult_obesity,food_environment_index,graduation_cohort,graduation_rate,%some_college,life_expectancy,%diabetes,%food_insecure,%limited_access,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
0,36001,New York,Albany,25,10,15,44,5821,14.21,27.3,8,3014,84.41,76.78,80.03,9.1,12,4.78,64536,35.5,12.79,0.2966,6.784,0.0674,6.101,71.81
1,36003,New York,Allegany,47,52,49,34,7283,14.42,35.9,8.1,502,87.85,61.37,78,10.9,12.4,2.992,46262,51.94,1.277,0.3166,1.294,0.04092,1.678,94.29
2,36005,New York,Bronx,62,62,36,62,6696,26.8,29,7.7,14750,67.51,51.17,80.56,12.5,16,0.0009199,38566,86.6,29.22,2.914,4.5,0.4148,56.37,9.131
3,36007,New York,Broome,52,37,51,49,7415,15.93,28,8,2205,82.95,67.26,78.67,10.6,12.8,3.241,50928,54.4,5.47,0.2682,4.427,0.06679,4.342,83
4,36009,New York,Cattaraugus,57,59,47,60,7255,16.37,37.6,8.1,1041,85.01,56.04,77.85,13.3,12.5,2.584,48017,50.84,1.378,3.548,0.8719,0.03774,2.124,90.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,36115,New York,Washington,41,38,42,37,6950,14.26,33.6,8.4,690,79.57,55.05,78.57,12.4,10.5,4.286,55913,46.45,2.94,0.3284,0.5589,0.03432,2.85,92.3
58,36117,New York,Wayne,40,33,45,26,7147,15.45,36.3,8.6,1164,87.2,64.36,78.69,12.1,9.8,3.489,61118,46.74,2.802,0.4164,0.6962,0.04108,4.473,89.83
59,36119,New York,Westchester,5,3,2,23,4258,14.8,20.7,9.1,11163,89.55,71.89,83.51,7.6,7.7,1.379,94521,36.18,13.8,0.9565,6.436,0.1323,25.14,53.09
60,36121,New York,Wyoming,18,28,25,9,6456,13.95,37.9,8.2,339,93.81,55.19,78.74,12.3,10.5,6.067,57709,43.36,5.119,0.4441,0.5638,0.02994,3.261,89.9
61,36123,New York,Yates,27,32,52,3,7491,14.67,29.5,8.8,214,78.5,50.89,78.21,14.3,9.9,0.5,51089,56.99,0.8856,0.3301,0.8252,0.02013,2.311,94.73

In [ ]:
#change data types
floats=['yppl','%poor_fair_health','%adult_obesity','food_environment_index','graduation_rate','%some_college','life_expectancy','%diabetes','%food_insecure',
        '%limited_access','%lunch_aid','%african_american','%american_indian','%asian','%pacific_islander','%hispanic','%white']

ints=['fips','health_outcomes_r','health_factors_r','length_life_r','quality_life_r','graduation_cohort','household_income']

rank2020[floats]=rank2020[floats].astype(float)
rank2020[ints]=rank2020[ints].astype(int)

#Save and export
pd.set_option("display.precision", 4)
rank2020
rank2020.to_csv('rank2020.csv',encoding='utf-8',index=False)

## Cleaning 2021 data
Resulting dataframe **rank2021**

### 1st Sheet: Outcomes & Factors Rankings

In [ ]:
df9=pd.read_excel('2021_health_r.xlsx',sheet_name='Outcomes & Factors Rankings')
df9

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Health Outcomes,Unnamed: 4,Health Factors,Unnamed: 6
0,FIPS,State,County,Z-Score,Rank,Z-Score,Rank
1,36000,New York,NaN,NaN,NaN,NaN,NaN
2,36001,New York,Albany,-0.3949,16,-0.6235,7
3,36003,New York,Allegany,0.5138,45,0.4648,54
4,36005,New York,Bronx,1.4,62,1.411,62
...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.246,39,0.2333,42
60,36117,New York,Wayne,0.2867,41,0.1168,36
61,36119,New York,Westchester,-1.4,4,-0.7589,5
62,36121,New York,Wyoming,-0.1858,26,0.09844,34
63,36123,New York,Yates,-0.0934,27,0.03156,29

In [ ]:
#Remove row
df9c=df9.drop([0,1])

#Renaming columns
new_col1={'Unnamed: 0': 'fips',
         'Unnamed: 1': 'state',
         'Unnamed: 2': 'county_name',
         'Health Outcomes': 'health_outcomes_z',
         'Unnamed: 4': 'health_outcomes_r',
         'Health Factors': 'health_factors_z',
         'Unnamed: 6': 'health_factors_r'}
df9c=df9c.rename(columns=new_col1)
df9c

,fips,state,county_name,health_outcomes_z,health_outcomes_r,health_factors_z,health_factors_r
2,36001,New York,Albany,-0.3949,16,-0.6235,7
3,36003,New York,Allegany,0.5138,45,0.4648,54
4,36005,New York,Bronx,1.4,62,1.411,62
5,36007,New York,Broome,0.5206,47,0.1476,38
6,36009,New York,Cattaraugus,1.1,58,0.5771,60
...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.246,39,0.2333,42
60,36117,New York,Wayne,0.2867,41,0.1168,36
61,36119,New York,Westchester,-1.4,4,-0.7589,5
62,36121,New York,Wyoming,-0.1858,26,0.09844,34
63,36123,New York,Yates,-0.0934,27,0.03156,29

### 2nd sheet: Outcomes & Factors SubRankings

In [ ]:
df10=pd.read_excel('2021_health_r.xlsx',sheet_name='Outcomes & Factors SubRankings')
df10

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Length of Life,Unnamed: 4,Quality of Life,Unnamed: 6,Health Behaviors,Unnamed: 8,Clinical Care,Unnamed: 10,Social & Economic Factors,Unnamed: 12,Physical Environment,Unnamed: 14
0,FIPS,State,County,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank,Z-Score,Rank
1,36000,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,36001,New York,Albany,-0.1773,17,-0.2176,15,-0.1482,13,-0.1644,5,-0.2691,7,-0.04184,6
3,36003,New York,Allegany,0.4706,53,0.04311,33,0.1549,47,0.09963,54,0.1993,53,0.01106,40
4,36005,New York,Bronx,0.1347,39,1.266,62,0.006684,28,0.3818,62,0.9759,62,0.04705,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,0.05398,32,0.1921,50,0.1794,50,0.06267,48,-0.03482,27,0.02602,50
60,36117,New York,Wayne,0.2007,41,0.08606,36,0.1173,43,0.1352,57,-0.1094,19,-0.02637,17
61,36119,New York,Westchester,-1.023,3,-0.378,9,-0.4655,2,-0.1566,7,-0.2321,9,0.09532,62
62,36121,New York,Wyoming,-0.1742,18,-0.01163,31,0.1286,44,0.07127,51,-0.1193,18,0.0179,44
63,36123,New York,Yates,0.5898,56,-0.6832,1,-0.05638,21,0.05179,45,0.03965,35,-0.003495,29

In [ ]:
#Remove columns
to_remove=df10.iloc[:,np.r_[1:3,7:15]]
df10c=df10.drop(columns=to_remove)

#Remove rows
df10c=df10c.drop([0,1])

#Rename columns
new_col10={'Unnamed: 0':'fips',
          'Length of Life':'lenght_life_z',
          'Unnamed: 4':'length_life_r',
          'Quality of Life':'quality_life_z',
          'Unnamed: 6':'quality_life_r'}
df10c=df10c.rename(columns=new_col10)
df10c

     fips lenght_life_z length_life_r quality_life_z quality_life_r
2   36001       -0.1773            17        -0.2176             15
3   36003        0.4706            53        0.04311             33
4   36005        0.1347            39          1.266             62
5   36007        0.3524            47         0.1682             47
6   36009        0.5605            55         0.5398             61
..    ...           ...           ...            ...            ...
59  36115       0.05398            32         0.1921             50
60  36117        0.2007            41        0.08606             36
61  36119        -1.023             3         -0.378              9
62  36121       -0.1742            18       -0.01163             31
63  36123        0.5898            56        -0.6832              1

[62 rows x 5 columns]

### 3rd Sheet: Ranked Measure Data

In [ ]:
df11=pd.read_excel('2021_health_r.xlsx',sheet_name='Ranked Measure Data')
df11

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Premature death,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Poor or fair health,Unnamed: 30,Unnamed: 31,Unnamed: 32,Poor physical health days,Unnamed: 34,Unnamed: 35,Unnamed: 36,Poor mental health days,Unnamed: 38,Unnamed: 39,Unnamed: 40,Low birthweight,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Adult smoking,Unnamed: 62,Unnamed: 63,Unnamed: 64,Adult obesity,Unnamed: 66,Unnamed: 67,Unnamed: 68,Food environment index,Unnamed: 70,Physical inactivity,Unnamed: 72,Unnamed: 73,Unnamed: 74,Access to exercise opportunities,Unnamed: 76,Excessive drinking,Unnamed: 78,Unnamed: 79,Unnamed: 80,Alcohol-impaired driving deaths,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Sexually transmitted infections,Unnamed: 88,Unnamed: 89,Teen births,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Uninsured,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Primary care physicians,Unnamed: 115,Unnamed: 116,Unnamed: 117,Dentists,Unnamed: 119,Unnamed: 120,Unnamed: 121,Mental health providers,Unnamed: 123,Unnamed: 124,Unnamed: 125,Preventable hospital stays,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Mammography screening,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Flu vaccinations,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,High school completion,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Some college,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unemployment,Unnamed: 160,Unnamed: 161,Unnamed: 162,Children in poverty,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Income inequality,Unnamed: 173,Unnamed: 174,Unnamed: 175,Children in single-parent households,Unnamed: 177,Unnamed: 178,Unnamed: 179,Unnamed: 180,Unnamed: 181,Social associations,Unnamed: 183,Unnamed: 184,Violent crime,Unnamed: 186,Unnamed: 187,Injury deaths,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Unnamed: 198,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Air pollution - particulate matter,Unnamed: 209,Drinking water violations,Unnamed: 211,Severe housing problems,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Driving alone to work,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Unnamed: 237,Unnamed: 238,Unnamed: 239,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Long commute - driving alone,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248
0,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,Z-Score,YPLL Rate (AIAN),YPLL Rate (AIAN) 95% CI - Low,YPLL Rate (AIAN) 95% CI - High,YPLL Rate (AIAN) Unreliable,YPLL Rate (Asian),YPLL Rate (Asian) 95% CI - Low,YPLL Rate (Asian) 95% CI - High,YPLL Rate (Asian) Unreliable,YPLL Rate (Black),YPLL Rate (Black) 95% CI - Low,YPLL Rate (Black) 95% CI - High,YPLL Rate (Black) Unreliable,YPLL Rate (Hispanic),YPLL Rate (Hispanic) 95% CI - Low,YPLL Rate (Hispanic) 95% CI - High,YPLL Rate (Hispanic) Unreliable,YPLL Rate (White),YPLL Rate (White) 95% CI - Low,YPLL Rate (White) 95% CI - High,YPLL Rate (White) Unreliable,% Fair or Poor Health,95% CI - Low,95% CI - High,Z-Score,Average Number of Physically Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Average Number of Mentally Unhealthy Days,95% CI - Low,95% CI - High,Z-Score,Unreliable,% Low birthweight,95% CI - Low,95% CI - High,Z-Score,% LBW (AIAN),% LBW (AIAN) 95% CI - Low,% LBW (AIAN) 95% CI - High,% LBW (Asian),% LBW (Asian) 95% CI - Low,% LBW (Asian) 95% CI - High,% LBW (Black),% LBW (Black) 95% CI - Low,% LBW (Black) 95% CI - High,% LBW (Hispanic),% LBW (Hispanic) 95% CI - Low,% LBW (Hispanic) 95% CI - High,% LBW (White),% LBW (White) 95% CI - Low,% LBW (White) 95% CI - High,% Smokers,95% CI - Low,95% CI - High,Z-Score,% Adults with Obesity,95% CI - Low,95% CI - High,Z-Score,Food Environment Index,Z-Score,% Physically Inactive,95% CI - Low,95% CI - High,Z-Score,% With Access to Exercise Opportunities,Z-Score,% Excessive Drinking,95% CI - Low,95% CI - High,Z-Score,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,95% CI - Low,95% CI - High,Z-Score,# Chlamydia Cases,Chlamydia Rate,Z-Score,Teen Birth Rate,95% CI - Low,95% CI - High,Z-Score,Teen Birth Rate (AIAN),Teen Birth Rate (AIAN) 95% CI - Low,Teen Birth Rate (AIAN) 95% CI - High,Teen Birth Rate (Asian),Teen Birth Rate (Asian) 95% CI - Low,Teen Birth Rate (Asian) 95% CI - High,Teen Birth Rate (Black),Teen Birth Rate (Black) 95% CI - Low,Teen Birth Rate (Black) 95% CI - High,Teen Birth Rate (Hispanic),Teen Birth Rate (Hispanic) 95% CI - Low,Teen Birth Rate (Hispanic) 95% CI - High,Teen Birth Rate (White),Teen Birth Rate (White) 95% CI - Low,Teen Birth Rate (White) 95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Z-Score,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,Z-Score,# Dentists,Dentist Rate,Dentist Ratio,Z-Score,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Z-Score,Preventable Hospitalization Rate,Z-Score,Preventable Hosp. Rate (AIAN),Preventable Hosp. Rate (Asian),Preventable Hosp. Rate (Black),Preventable Hosp. Rate (Hispanic),Preventable Hosp. Rate (White),% With Annual Mammogram,Z-Score,% Screened (AIAN),% Screened (Asian),% Screened (Black),% Screened (Hispanic),% Screened (White),% Vaccinated,Z-Score,% Vaccinated (AIAN),% Vaccinated (Asian),% Vaccinated (Black),% Vaccinated (Hispanic),% Vaccinated (White),# Completed High School,Population,% Completed High School,95% CI - Low,95% CI - High,Z-Score,# Some College,Population,% Some College,95% CI - Low,95% CI - High,Z-Score,# Unemployed,Labor Force,% Unemployed,Z-Score,% Children in Poverty,95% CI - Low,95% CI - High,Z-Score,% Children in Poverty (AIAN),% Children in Poverty (Asian),% Children in Poverty (Black),% Children in Poverty (Hispanic),% Children in Poverty (White),80th Percentile Income,20th Percentile Income,Income Ratio,Z-Score,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,95% CI - Low,95% CI - High,Z-Score,# Associations,Social Association Rate,Z-Score,Annual Average Violent Crimes,Violent Crime Rate,Z-Score,# Injury Deaths,Injury Death Rate,95% CI - Low,95% CI - High,Z-Score,Injury Death Rate (AIAN),Injury Death Rate (AIAN) 95% CI - Low,Injury Death Rate (AIAN) 95% CI - High,Injury Death Rate (Asian),Injury Death Rate (Asian) 95% CI - Low,Injury Death Rate (Asian) 95% CI - High,Injury Death Rate (Black),Injury Death Rate (Black) 95% CI - Low,Injury Death Rate (Black) 95% CI - High,Injury Death Rate (Hispanic),Injury Death Rate (Hispanic) 95% CI - Low,Injury Death Rate (Hispanic) 95% CI - High,Injury Death Rate (White),Injury Death Rate (White) 95% CI - Low,Injury Death Rate (White) 95% CI - High,Average Daily PM2.5,Z-Score,Presence of Water Violation,Z-Score,% Severe Housing Problems,95% CI - Low,95% CI - High,Severe Housing Cost Burden,Severe Housing Cost Burden 95% CI - Low,Severe Housing Cost Burden 95% CI - High,Overcrowding,Overcrowding 95% CI - Low,Overcrowding 95% CI - High,Inadequate Facilities,Inadequate Facilities 95% CI - Low,Inadequate Facilities 95% CI - High,Z-Score,% Drive Alone to Work,95% CI - Low,95% CI - High,Z-Score,% Drive Alone (AIAN),% Drive Alone (AIAN) 95% CI - Low,% Drive Alone (AIAN) 95% CI - High,% Drive Alone (Asian),% Drive Alone (Asian) 95% CI - Low,% Drive Alone (Asian) 95% CI - High,% Drive Alone (Black),% Drive Alone (Black) 95% CI - Low,% Drive Alone (Black) 95% CI - High,% Drive Alone (Hispanic),% Drive Alone (Hispanic) 95% CI - Low,% Drive Alone (Hispanic) 95% CI - High,% Drive Alone (White),% Drive Alone (White) 95% CI - Low,% Drive Alone (White) 95% CI - High,# Workers who Drive Alone,% Long Commute - Drives Alone,95% CI - Low,95% CI - High,Z-Score
1,36000,New York,NaN,NaN,191195,5406,5370,5443,NaN,4789,4227,5351,NaN,2642,2554,2731,NaN,7772,7660,7883,NaN,4477,4405,4550,NaN,5350,5299,5400,NaN,16.25,15.55,16.98,NaN,3.561,3.407,3.716,NaN,3.612,3.464,3.76,NaN,NaN,7.965,7.923,8.007,NaN,8.972,8.016,9.928,8.456,8.327,8.585,12.39,12.26,12.52,7.998,7.911,8.085,6.445,6.391,6.499,12.96,12.3,13.65,NaN,26.4,NaN,NaN,NaN,9,NaN,23.4,NaN,NaN,NaN,93.19,NaN,19.17,18.37,20.01,NaN,1042,5057,20.61,19.92,21.3,NaN,119571,602.4,NaN,13.94,13.83,14.05,NaN,12.24,10.65,13.83,3.762,3.558,3.965,19.36,19.03,19.68,26.41,26.08,26.74,8.494,8.373,8.615,1007242,6.328,6.209,6.447,NaN,16366,83.75,1194:1,NaN,16575,85.2,1174:1,NaN,59204,304.3,329:1,NaN,4043,NaN,6021,2656,5752,4907,3766,42,NaN,33,31,35,33,45,50,NaN,29,52,34,39,53,11835343,13631937,86.82,86.72,86.92,NaN,3638743,5298957,68.67,68.38,68.96,NaN,376832,9514386,3.961,NaN,18.2,17.6,18.8,NaN,27.44,16.92,29.45,29.21,12.44,144703,25183,5.746,NaN,1101711,4083011,26.98,26.68,27.28,NaN,15832,8.101,NaN,7.484e+04,379,NaN,49646,50.46,50.02,50.9,NaN,45.75,38.7,52.79,18.83,17.93,19.73,48.89,47.76,50.01,35.78,34.92,36.63,59.79,59.14,60.43,6.6,NaN,NaN,NaN,23.54,23.41,23.67,19.52,19.39,19.65,5.074,5.003,5.145,0.9316,0.9023,0.9609,NaN,53.02,52.91,53.14,NaN,45.02,42.97,47.06,31.03,30.66,31.41,37.96,37.58,38.35,34.83,34.48,35.17,63,62.89,63.12,9300315,38.7,38.46,38.94,NaN
2,36001,New York,Albany,NaN,3336,6039,5716,6363,-0.3546,NaN,NaN,NaN,NaN,2228,1599,3022,NaN,1.058e+04,9442,1.171e+04,NaN,5765,4553,6978,NaN,5553,5187,5920,NaN,13.5,11.65,15.33,-1.371,3.309,2.973,3.64,-1.926,4.09,3.739,4.432,-1.02,NaN,8.143,7.774,8.511,1.07,NaN,NaN,NaN,8.129,6.997,9.261,12.31,11.31,13.31,9.489,8.119,10.86,6.651,6.222,7.08,16.59,13.88,19.21,-1.042,27.8,25.4,30,-0.7637,8.4,-0.2394,19.7,17.8,21.7,-1.341,92.06,-0.8691,22.05,21.38,22.67,0.5509,26,95,27.37,22.1,32.8,0.5448,1932,624,1.206,9.776,9.102,10.45,-0.9214,NaN,NaN,NaN,4.478,2.975,6.472,25.29,22.67,27.91,21.17,17.74,24.59,4.934,4.348,5.521,10070,4.168,3.573,4.764,-1.043,299,97.36,1027:1,-1.218,283,92.63,1080:1,-1.203,1147,375.4,266:1,-1.225,3983,-0.4993,NaN,1574,7429,3986,3617,46,0.03159,NaN,41,39,28,47,55,-1.088,NaN,51,39,50,57,188812,204918,92.14,91.63,92.65,-0.8448,58023,75215,77.14,74.73,79.56,-1.774,5745,157444,3.649,-1.066,16,12.54,19.46,-0.4161,12.86,7.067,36.12,39.51,7.704,131267,27048,4.853,0.2101,17503,56284,31.1,28.28,33.91,1.3,453,14.75,-1.386,1074,348.2,0.9027,745,48.36,44.89,51.83,-1.045,NaN,NaN,NaN,15.91,9.269,25.48,46.97,38.13,57.24,33.51,22.77,47.56,52.67,48.44,56.9,6.6,-0.1583,No,-0.9298,15.43,14.55,16.31,14.37,13.55,15.18,0.8774,0.6777,1.077,0.8096,0.5821,1.037,-0.18,75.34,74.33,76.34,0.04765,NaN,NaN,NaN,61.2,57.23,65.17,58.24,54.54,61.94,57.62,52.69,62.54,83.84,83.03,84.65,157933,21.2,20.07,22.33,-1.199
3,36003,New York,Allegany,NaN,637,7433,6498,8369,0.9413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.51,15.05,20,0.2659,4.423,3.995,4.85,0.9984,4.672,4.246,5.066,0.7981,NaN,6.578,5.734,7.422,-0.8156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.32,18.74,25.51,0.6482,36.6,33.3,40.2,1.015,8,0.6087,27.8,24.9,30.8,0.8303,62.36,1.121,20.21,19.3,21.1,-0.495,5,16,31.25,17.75,44.91,0.9503,158,336.9,-0.2046,13.93,12.02,15.84,-0.2788,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1916,5.709,4.756,6.662,0.3428,21,45.23,2211:1,0.5106,16,34.71,2881:1,0.7759,109,236.5,423:1,-0.08813,5154,1.199,NaN,NaN,NaN,NaN,NaN,49,-0.5559,NaN,NaN,NaN,NaN,NaN,49,0.5709,NaN,NaN,NaN,NaN,NaN,27268,30038,90.78,89.88,91.68,-0.4614,5820,9318,62.46,58.6,66.32,0.07309,1061,19441,5.458,1.729,26.8,20.13,33.47,1.504,NaN,NaN,NaN,41.26,26.57,89353,21445,4.167,-0.6031,2127,9386,22.66,18.68,26.65,-0.06881,72,15.51,-1.63,91.5,195,-0.2138,137,58.56,48.75,68.36,-0.1655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.6,-0.1583,Yes,1.058,13.99,12.37,15.6,10.52,9.221,11.82,1.848,1.191,2.505,2.566,1.908,3.223,-0.4406,75.81,73.89,77.73,0.07776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.35,8.026,40.68,75.56,73.5,77.62,19545,30.2,28.17,32.23,-0.4179
4,36005,New York,Bronx,NaN,15102,6711,6567,6854,0.2693,NaN,NaN,NaN,NaN,3518,2921,4116,NaN,8488,8185,8790,NaN,5477,5306,5647,NaN,7881,7312,8450,NaN,29.32,26.44,32.14,5.09,4.762,4.393,5.111,1.889,4.462,4.152,4.75,0.1425,NaN,9.552,9.401,9.703,2.768,13.46,6.902,20.02,10.65,9.926,11.36,11.74,11.44,12.05,8.568,8.378,8.757,7.578,7.081,8.076,18.16,16.19,20,-0.5787,28.5,26.1,31.1,-0.6222,7.4,1.881,29.9,27.6,32.3,1.393,100,-1.401,16.49,15.93,17.03,-2.602,25,192,13.02,9.758,16.69,-0.9539,17689,1202,4.048,23.97,23.45,24.49,1.276,NaN,NaN,NaN,5.941,4.614,7.532,19.32,18.45,20.2,28.61,27.87,29.34,10.74,9.409,12.07,104490,8.693,7.978,9.408,3.027,872,60.89,1642:1,-0.008824,775,54.65,1830:1,0.09487,3052,215.2,465:1,0.0861,5474,1.662,1806,3509,6020,6490,4119,32,2.773,NaN,25,33,28,37,40,3.06,37,48,35,34,49,676297,929546,72.76,72.31,73.2,4.612,212819,409835,51.93,50.9,52.95,1.398,32035,597677,5.36,1.578,36.5,33.28,39.72,3.228,47.45,31.71,37.6,42.03,18.8,89461,13233,6.76,2.469,177411,353456,50.19,48.96,51.43,4.399,387,2.702,2.485,8486,586.1,2.636,3558,49.19,47.58,50.81,-0.9734,NaN,NaN,NaN,15.41,11.28,20.55,52.46,49.41,55.51,42.73,40.72,44.75,82.56,75.78,89.35,8.2,1.53,No,-0.9298,38.7,38.1,39.29,30.38,29.79,30.97,12.35,11.91,12.79,0.9448,0.8123,1.077,4.02,23.5,22.91,24.08,-3.25,28.07,16.29,39.85,42.53,39.87,45.19,34.56,32.91,36.22,28.89,27.79,29.98,58.5,57.06,59.94,582554,54.2,52.42,55.98,1.665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,New York,Washington,NaN,810,6537,5764,7310,0.108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.2,15.62,20.83,0.5501,4.242,3.795,4.68,0.5237,4.599,4.195,5.018,0.5706,NaN,7.369,6.56,8.179,0.1381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.54,20.83,27.86,1.304,35,32,38.1,0.692,8.4,-0.2394,26,23.4,29,0.3477,66.04,0.8746,21.45,20.52,22.4,0.2078,6,34,17.65,9.351,27.49,-0.4707,137,222.3,-0.7677,23.28,20.44,26.11,1.169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2515,5.388,4.554,6.222,0.05408,21,34.32,2914:1,0.8726,14,22.87,4372:1,1.18,86,140.5,712:1,0.6974,4422,0.1372,NaN,NaN,NaN,NaN,NaN,46,0.03159,NaN,NaN,NaN,46,46,50,0.2944,NaN,NaN,25,44,50,39552,44992,87.91,86.37,89.45,0.3463,8155,14798,55.11,50.76,59.45,0.9977,1133,27831,4.071,-0.4133,17.2,11.6,22.8,-0.2027,NaN,NaN,3.226,25.69,14.99,104571,26168,3.996,-0.805,2562,11722,21.86,17.27,26.44,-0.1995,57,9.314,0.3605,88,141.1,-0.607,166,53.89,45.69,62.08,-0.5685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.5,-0.2638,Yes,1.058,14.71,12.84,16.59,13.14,11.45,14.82,1.501,0.8789,2.122,0.6669,0.3812,0.9527,-0.3091,81.71,79.5,83.91,0.453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28433,38.8,35.92,41.68,0.3283
60,36117,New York,Wayne,NaN,1194,6853,6205,7500,0.4014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.35,14.18,18.97,-0.2053,4.256,3.855,4.728,0.5598,4.588,4.192,5.01,0.5355,NaN,7.243,6.623,7.862,-0.01469,NaN,NaN,NaN,NaN,NaN,NaN,9.091,5.384,12.8,7.792,5.115,10.47,7.161,6.509,7.812,22.83,19.56,26.34,0.8002,37.3,34.2,40.2,1.157,8.5,-0.4514,30.6,27.8,33.5,1.581,61.89,1.153,18.25,17.42,19.02,-1.608,9,55,16.36,9.932,23.86,-0.6047,291,320.9,-0.2832,17.73,15.84,19.62,0.31,NaN,NaN,NaN,NaN,NaN,NaN,32.04,21.29,46.3,31.54,22.21,43.48,16.23,14.3,18.16,3527,4.848,4.133,5.563,-0.432,23,25.54,3916:1,1.164,45,50.05,1998:1,0.2521,95,105.7,947:1,0.9827,5551,1.774,81818,4433,3273,2718,5470,42,0.815,NaN,NaN,40,43,43,51,0.01784,NaN,29,51,50,51,56980,63914,89.15,88.1,90.2,-0.003331,12809,19963,64.16,60.54,67.79,-0.1412,1765,43835,4.026,-0.4822,15.8,10.91,20.69,-0.4516,NaN,22.33,40,27.78,14.44,108877,26927,4.043,-0.749,3976,19403,20.49,17.08,23.91,-0.4209,92,10.21,0.071,163,178.4,-0.3347,307,67.79,60.2,75.37,0.6305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.7,-0.05276,No,-0.9298,11.66,10.37,12.95,10.17,8.887,11.45,1.476,0.9176,2.035,0.6971,0.3961,0.9981,-0.8607,83.98,82.64,85.32,0.5977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.17,43.32,71.03,83.29,81.26,85.32,43773,39,36.83,41.17,0.3457
61,36119,New York,Westchester,NaN,7347,4221,4069,4373,-2.045,NaN,NaN,NaN,NaN,2311,1821,2801,NaN,6580,6109,7051,NaN,3429,3175,3683,NaN,4055,3835,4276,NaN,13.72,11.99,15.57,-1.281,3.317,3.005,3.646,-1.905,3.69,3.396,4.004,-2.266,NaN,7.949,7.752,8.146,0.8363,NaN,NaN,NaN,8.633,7.882,9.383,12.23,11.61,12.84,7.293,6.974,7.611,6.775,6.491,7.058,12.6,10.6,14.67,-2.219,21.6,19.8,23.7,-2.017,9.2,-1.936,19.4,17.6,21.2,-1.422,99.62,-1.376,19.05,18.5,19.56,-1.154,34,175,19.43,15.69,23.41,-0.2846,3925,400.4,0.1074,8.337,7.963,8.712,-1.144,NaN,NaN,NaN,1.623,1.04,2.415,13.27,12.04,14.49,20.73,19.59,21.87,1.302,1.096,1.509,45723,5.805,5.209,6.401,0.4291,1345,139,719:1,-2.6,1093,113,885:1,-1.898,3901,403.2,248:1,-1.453,3678,-0.9415,NaN,2359,5799,4538,3290,46,0.03159,NaN,35,40,38,49,54,-0.8117,44,52,38,43,58,588528,668290,88.06,87.67,88.46,0.3025,169610,234081,72.46,71.15,73.77,-1.185,18224,484382,3.762,-0.8903,10.1,7.598,12.6,-1.465,12.94,10.21,18.86,18.44,3.228,214529,34242,6.265,1.883,44512,213194,20.88,19.74,22.02,-0.3581,829,8.567,0.6005,2148,220.6,-0.0274,2006,41.22,39.42,43.03,-1.661,NaN,NaN,NaN,19.76,15.18,25.28,41.83,37.01,46.64,25.24,22.41,28.08,50.55,47.83,53.26,9,2.374,Yes,1.058,23.51,22.96,24.07,20.14,19.58,20.71,4.189,3.879,4.5,0.7719,0.6475,0.8964,1.279,57.47,56.81,58.12,-1.089,48.64,39.16,58.12,64.48,61.62,67.34,57.82,56.04,59.6,56.71,55.32,58.11,78.52,77.79,79.26,471725,41.6,40.51,42.69,0.5713

In [ ]:
#Deleting columns
to_remove=df11.iloc[:,np.r_[1:5,6:29,30:65,66:69,70:155,156:249]]
df11c=df11.drop(columns=to_remove)

#Deleting rows
df11c=df11c.drop([0,1])

#Renaming columns
new_col11= {'Unnamed: 0':'fips',
          'Unnamed: 5':'yppl',
          'Poor or fair health':'%poor_fair_health',
          'Adult obesity':'%adult_obesity',
          'Food environment index':'food_environment_index',
          'Unnamed: 155':'%some_college'}

df11c=df11c.rename(columns=new_col11)
df11c

,fips,yppl,%poor_fair_health,%adult_obesity,food_environment_index,%some_college
2,36001,6039,13.5,27.8,8.4,77.14
3,36003,7433,17.51,36.6,8,62.46
4,36005,6711,29.32,28.5,7.4,51.93
5,36007,7179,16.96,30.1,8,66.72
6,36009,7627,19.62,38.9,8.1,55.57
...,...,...,...,...,...,...
59,36115,6537,18.2,35,8.4,55.11
60,36117,6853,16.35,37.3,8.5,64.16
61,36119,4221,13.72,21.6,9.2,72.46
62,36121,6046,17.62,37.9,8.3,56.36
63,36123,7690,15.72,31.6,8.9,54.44

### 4th sheet: Additional Measure Data

In [ ]:
df12=pd.read_excel('2021_health_r.xlsx',sheet_name='Additional Measure Data')
df12

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Life expectancy,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Premature age-adjusted mortality,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Child mortality,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Infant mortality,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Frequent physical distress,Unnamed: 79,Unnamed: 80,Frequent mental distress,Unnamed: 82,Unnamed: 83,Diabetes prevalence,Unnamed: 85,Unnamed: 86,HIV prevalence,Unnamed: 88,Food insecurity,Unnamed: 90,Limited access to healthy foods,Unnamed: 92,Drug overdose deaths,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Motor vehicle crash deaths,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Insufficient sleep,Unnamed: 132,Unnamed: 133,Uninsured adults,Unnamed: 135,Unnamed: 136,Unnamed: 137,Uninsured children,Unnamed: 139,Unnamed: 140,Unnamed: 141,Other primary care providers,Unnamed: 143,High school graduation,Unnamed: 145,Disconnected youth,Unnamed: 147,Unnamed: 148,Reading scores,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Math scores,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Median household income,Unnamed: 160,Unnamed: 161,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,Unnamed: 172,Unnamed: 173,Unnamed: 174,Unnamed: 175,Unnamed: 176,Children eligible for free or reduced price lunch,Residential segregation - Black/White,Residential segregation - non-White/White,Homicides,Unnamed: 181,Unnamed: 182,Unnamed: 183,Unnamed: 184,Unnamed: 185,Unnamed: 186,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196,Unnamed: 197,Suicides,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208,Unnamed: 209,Unnamed: 210,Unnamed: 211,Unnamed: 212,Unnamed: 213,Unnamed: 214,Unnamed: 215,Unnamed: 216,Unnamed: 217,Firearm fatalities,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235,Unnamed: 236,Juvenile arrests,Unnamed: 238,Unnamed: 239,Unnamed: 240,Traffic volume,Homeownership,Unnamed: 243,Unnamed: 244,Unnamed: 245,Severe housing cost burden,Unnamed: 247,Unnamed: 248,Unnamed: 249,Broadband access,Unnamed: 251,Unnamed: 252,Unnamed: 253,Population,% below 18 years of age,% 65 and older,% Non-Hispanic Black,Unnamed: 258,% American Indian & Alaska Native,Unnamed: 260,% Asian,Unnamed: 262,% Native Hawaiian/Other Pacific Islander,Unnamed: 264,% Hispanic,Unnamed: 266,% Non-Hispanic White,Unnamed: 268,% not proficient in English,Unnamed: 270,Unnamed: 271,Unnamed: 272,% Females,% Rural,Unnamed: 275
0,FIPS,State,County,Life Expectancy,95% CI - Low,95% CI - High,Life Expectancy (AIAN),Life Expectancy (AIAN) 95% CI - Low,Life Expectancy (AIAN) 95% CI - High,Life Expectancy (Asian),Life Expectancy (Asian) 95% CI - Low,Life Expectancy (Asian) 95% CI - High,Life Expectancy (Black),Life Expectancy (Black) 95% CI - Low,Life Expectancy (Black) 95% CI - High,Life Expectancy (Hispanic),Life Expectancy (Hispanic) 95% CI - Low,Life Expectancy (Hispanic) 95% CI - High,Life Expectancy (White),Life Expectancy (White) 95% CI - Low,Life Expectancy (White) 95% CI - High,# Deaths,Age-Adjusted Death Rate,95% CI - Low,95% CI - High,Age-Adjusted Mortality (AIAN),Age-Adjusted Mortality (AIAN) 95% CI - Low,Age-Adjusted Mortality (AIAN) 95% CI - High,Age-Adjusted Mortality (Asian),Age-Adjusted Mortality (Asian) 95% CI - Low,Age-Adjusted Mortality (Asian) 95% CI - High,Age-Adjusted Mortality (Black),Age-Adjusted Mortality (Black) 95% CI - Low,Age-Adjusted Mortality (Black) 95% CI - High,Age-Adjusted Mortality (Hispanic),Age-Adjusted Mortality (Hispanic) 95% CI - Low,Age-Adjusted Mortality (Hispanic) 95% CI - High,Age-Adjusted Mortality (White),Age-Adjusted Mortality (White) 95% CI - Low,Age-Adjusted Mortality (White) 95% CI - High,# Deaths,Child Mortality Rate,95% CI - Low,95% CI - High,Child Mortality Rate (AIAN),Child Mortality Rate (AIAN) 95% CI - Low,Child Mortality Rate (AIAN) 95% CI - High,Child Mortality Rate (Asian),Child Mortality Rate (Asian) 95% CI - Low,Child Mortality Rate (Asian) 95% CI - High,Child Mortality Rate (Black),Child Mortality Rate (Black) 95% CI - Low,Child Mortality Rate (Black) 95% CI - High,Child Mortality Rate (Hispanic),Child Mortality Rate (Hispanic) 95% CI - Low,Child Mortality Rate (Hispanic) 95% CI - High,Child Mortality Rate (White),Child Mortality Rate (White) 95% CI - Low,Child Mortality Rate (White) 95% CI - High,# Deaths,Infant Mortality Rate,95% CI - Low,95% CI - High,Infant Mortality Rate (AIAN),Infant Mortality Rate (AIAN) 95% CI - Low,Infant Mortality Rate (AIAN) 95% CI - High,Infant Mortality Rate (Asian),Infant Mortality Rate (Asian) 95% CI - Low,Infant Mortality Rate (Asian) 95% CI - High,Infant Mortality Rate (Black),Infant Mortality Rate (Black) 95% CI - Low,Infant Mortality Rate (Black) 95% CI - High,Infant Mortality Rate (Hispanic),Infant Mortality Rate (Hispanic) 95% CI - Low,Infant Mortality Rate (Hispanic) 95% CI - High,Infant Mortality Rate (White),Infant Mortality Rate (White) 95% CI - Low,Infant Mortality Rate (White) 95% CI - High,% Frequent Physical Distress,95% CI - Low,95% CI - High,% Frequent Mental Distress,95% CI - Low,95% CI - High,% Adults with Diabetes,95% CI - Low,95% CI - High,# HIV Cases,HIV Prevalence Rate,# Food Insecure,% Food Insecure,# Limited Access,% Limited Access to Healthy Foods,# Drug Overdose Deaths,Drug Overdose Mortality Rate,95% CI - Low,95% CI - High,Drug Overdose Mortality Rate (AIAN),Drug Overdose Mortality Rate (AIAN) 95% CI - Low,Drug Overdose Mortality Rate (AIAN) 95% CI - High,Drug Overdose Mortality Rate (Asian),Drug Overdose Mortality Rate (Asian) 95% CI - Low,Drug Overdose Mortality Rate (Asian) 95% CI - ...,Drug Overdose Mortality Rate (Black),Drug Overdose Mortality Rate (Black) 95% CI - Low,Drug Overdose Mortality Rate (Black) 95% CI - ...,Drug Overdose Mortality Rate (Hispanic),Drug Overdose Mortality Rate (Hispanic) 95% CI...,Drug Overdose Mortality Rate (Hispanic) 95% CI...,Drug Overdose Mortality Rate (White),Drug Overdose Mortality Rate (White) 95% CI - Low,Drug Overdose Mortality Rate (White) 95% CI - ...,# Motor Vehicle Deaths,Motor Vehicle Mortality Rate,95% CI - Low,95% CI - High,MV Mortality Rate (AIAN),MV Mortality Rate (AIAN) 95% CI - Low,MV Mortality Rate (AIAN) 95% CI - High,MV Mortality Rate (Asian),MV Mortality Rate (Asian) 95% CI - Low,MV Mortality Rate (Asian) 95% CI - High,MV Mortality Rate (Black),MV Mortality Rate (Black) 95% CI - Low,MV Mortality Rate (Black) 95% CI - High,MV Mortality Rate (Hispanic),MV Mortality Rate (Hispanic) 95% CI - Low,MV Mortality Rate (Hispanic) 95% CI - High,MV Mortality Rate (White),MV Mortality Rate (White) 95% CI - Low,MV Mortality Rate (White) 95% CI - High,% Insufficient Sleep,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,# Uninsured,% Uninsured,95% CI - Low,95% CI - High,Other Primary Care Provider Rate,Other Primary Care Provider Ratio,Cohort Size,High School Graduation Rate,% Disconnected Youth,95% CI - Low,95% CI - High,Average Grade Performance,Average Grade Performance (Asian),Average Grade Performance (Black),Average Grade Performance (Hispanic),Average Grade Performance (White),Average Grade Performance,Average Grade Performance (Asian),Average Grade Performance (Black),Average Grade Performance (Hispanic),Average Grade Performance (White),Median Household Income,95% CI - Low,95% CI - High,Household Income (AIAN),Household Income (AIAN) 95% CI - Low,Household Income (AIAN) 95% CI - High,Household Income (Asian),Household Income (Asian) 95% CI - Low,Household Income (Asian) 95% CI - High,Household Income (Black),Household Income (Black) 95% CI - Low,Household Income (Black) 95% CI - High,Household Income (Hispanic),Household Income (Hispanic) 95% CI - Low,Household Income (Hispanic) 95% CI - High,Household Income (White),Household Income (White) 95% CI - Low,Household Income (White) 95% CI - High,% Enrolled in Free or Reduced Lunch,Segregation index,Segregation Index,Homicide Rate,95% CI - Low,95% CI - High,Homicide Rate (AIAN),Homicide Rate (AIAN) 95% CI - Low,Homicide Rate (AIAN) 95% CI - High,Homicide Rate (Asian),Homicide Rate (Asian) 95% CI - Low,Homicide Rate (Asian) 95% CI - High,Homicide Rate (Black),Homicide Rate (Black) 95% CI - Low,Homicide Rate (Black) 95% CI - High,Homicide Rate (Hispanic),Homicide Rate (Hispanic) 95% CI - Low,Homicide Rate (Hispanic) 95% CI - High,Homicide Rate (White),Homicide Rate (White) 95% CI - Low,Homicide Rate (White) 95% CI - High,# Deaths,Suicide Rate (Age-Adjusted),95% CI - Low,95% CI - High,Crude Rate,Suicide Rate (AIAN),Suicide Rate (AIAN) 95% CI - Low,Suicide Rate (AIAN) 95% CI - High,Suicide Rate (Asian),Suicide Rate (Asian) 95% CI - Low,Suicide Rate (Asian) 95% CI - High,Suicide Rate (Black),Suicide Rate (Black) 95% CI - Low,Suicide Rate (Black) 95% CI - High,Suicide Rate (Hispanic),Suicide Rate (Hispanic) 95% CI - Low,Suicide Rate (Hispanic) 95% CI - High,Suicide Rate (White),Suicide Rate (White) 95% CI - Low,Suicide Rate (White) 95% CI - High,# Firearm Fatalities,Firearm Fatalities Rate,95% CI - Low,95% CI - High,Firearm Fatalities Rate (AIAN),Firearm Fatalities Rate (AIAN) 95% CI - Low,Firearm Fatalities Rate (AIAN) 95% CI - High,Firearm Fatalities Rate (Asian),Firearm Fatalities Rate (Asian) 95% CI - Low,Firearm Fatalities Rate (Asian) 95% CI - High,Firearm Fatalities Rate (Black),Firearm Fatalities Rate (Black) 95% CI - Low,Firearm Fatalities Rate (Black) 95% CI - High,Firearm Fatalities Rate (Hispanic),Firearm Fatalities Rate (Hispanic) 95% CI - Low,Firearm Fatalities Rate (Hispanic) 95% CI - High,Firearm Fatalities Rate (White),Firearm Fatalities Rate (White) 95% CI - Low,Firearm Fatalities Rate (White) 95% CI - High,Non-Petitioned Cases,Petitioned Cases,Denominator,Juvenile Arrest Rate,Traffic Volume,# Homeowners,% Homeowners,95% CI - Low,95% CI - High,# Households with Severe Cost Burden,% Severe Housing Cost Burden,95% CI - Low,95% CI - High,% Broadband Access,Numerator,95% CI - Low,95% CI - High,Population,% Less Than 18 Years of Age,% 65 and Over,# Black,% Black,# American Indian & Alaska Native,% American Indian & Alaska Native,# Asian,% Asian,# Native Hawaiian/Other Pacific Islander,% Native Hawaiian/Other Pacific Islander,# Hispanic,% Hispanic,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural
1,36000,New York,NaN,81.44,81.39,81.48,94.09,91.37,96.81,90.04,89.76,90.32,79.54,79.41,79.68,85.39,85.22,85.55,81.05,81,81.1,191195,276.3,275.1,277.6,232.5,212.2,252.7,134.5,131.5,137.6,384,380,388,225.5,222.6,228.5,275.9,274.2,277.5,6334,38.55,37.6,39.5,24.02,13.73,39.01,26.92,24.21,29.62,65.2,62.16,68.24,30.89,29.19,32.6,32.63,31.39,33.87,7387,4.511,4.408,4.614,NaN,NaN,NaN,3.095,2.799,3.391,7.238,6.93,7.546,3.275,3.106,3.445,3.887,3.747,4.026,10.57,9.989,11.19,11.11,10.51,11.73,10.1,NaN,NaN,127162,765.3,2166060,11.1,4.435e+05,2.289,11235,19.09,18.74,19.45,24.55,18.34,32.2,3.169,2.694,3.645,19.07,18.16,19.97,17.03,16.27,17.79,21.73,21.23,22.23,7788,5.652,5.527,5.778,5.64,3.748,8.151,3.056,2.747,3.365,5.212,4.902,5.522,4.58,4.32,4.84,6.465,6.287,6.644,38.91,37.93,39.91,914338,7.668,7.43,7.907,103277,2.456,2.217,2.694,127,787:1,206896,82.38,6.047,5.835,6.259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72038,7.15e+04,7.257e+04,41509,3.893e+04,4.409e+04,76341,7.538e+04,7.73e+04,48557,4.8e+04,4.911e+04,49159,4.851e+04,4.981e+04,78782,7.836e+04,7.92e+04,53.86,73.48,60.85,3.193,3.098,3.287,2.82,1.542,4.731,0.9535,0.7807,1.126,11.42,10.96,11.88,3.387,3.164,3.61,1.217,1.139,1.294,8442,8.122,7.945,8.3,8.58,4.978,2.9,7.971,5.356,4.878,5.834,4.897,4.54,5.255,4.252,3.951,4.554,10.46,10.19,10.74,4146,4.214,4.086,4.342,NaN,NaN,NaN,0.6381,0.4833,0.8267,9.005,8.523,9.487,2.326,2.108,2.544,4.078,3.91,4.246,3285,3747,1345800,5.225,1684,3957802,53.9,53.58,54.22,1392053,19.55,19.43,19.67,82.84,6083283,82.57,83.12,19453561,20.71,16.94,2813773,14.46,189748,0.9754,1753199,9.012,27034,0.139,3751058,19.28,10755420,55.29,1276742,6.932,6.862,7.002,51.43,2349997,12.13
2,36001,New York,Albany,79.95,79.63,80.27,NaN,NaN,NaN,88.8,85.64,91.96,76.13,74.9,77.36,84.83,81.51,88.16,80.37,80.02,80.72,3336,305.7,294.9,316.4,NaN,NaN,NaN,123.4,93.72,159.6,524.4,482,566.8,269.3,217,321.5,286.9,274.9,298.8,103,45.3,36.55,54.05,NaN,NaN,NaN,NaN,NaN,NaN,84.47,59.48,116.4,54.91,28.37,95.92,34.74,25.7,45.92,129,6.07,5.022,7.117,NaN,NaN,NaN,NaN,NaN,NaN,15,11.3,19.53,NaN,NaN,NaN,4.057,3.064,5.268,10.03,8.916,11.15,12.4,11.1,13.67,9.7,8.3,11.1,1146,429,31210,10.2,1.454e+04,4.78,158,17.13,14.46,19.8,NaN,NaN,NaN,NaN,NaN,NaN,19.9,12.88,29.38,21.31,11.01,37.23,17.54,14.38,20.71,109,5.057,4.107,6.006,NaN,NaN,NaN,NaN,NaN,NaN,6.224,3.689,9.836,NaN,NaN,NaN,4.962,3.929,6.184,38.61,37.09,40.04,9023,4.849,4.134,5.564,1196,2.031,1.435,2.627,208.8,479:1,3009,84.92,3.596,2.412,4.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69408,6.447e+04,7.434e+04,48142,1.597e+04,8.032e+04,82181,7.159e+04,9.277e+04,31647,2.984e+04,3.345e+04,41682,3.449e+04,4.887e+04,74805,7.328e+04,7.633e+04,40.62,58.44,43.53,2.83,2.165,3.635,NaN,NaN,NaN,NaN,NaN,NaN,12.45,8.718,17.23,NaN,NaN,NaN,1.193,0.7185,1.864,159,9.673,8.118,11.23,10.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85,5.518,4.407,6.823,NaN,NaN,NaN,NaN,NaN,NaN,11.02,6.988,16.54,NaN,NaN,NaN,5.223,3.976,6.737,112,112,18800,11.91,801.6,71341,56.38,55.48,57.27,17691,14.24,13.36,15.13,83.53,105695,82.77,84.28,305506,18.25,17.44,39031,12.78,930,0.3044,20885,6.836,202,0.06612,19102,6.253,218645,71.57,5366,1.842,1.556,2.127,51.62,29496,9.696
3,36003,New York,Allegany,77.91,77.08,78.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,637,367.7,337.1,398.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,39.68,22.21,65.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.38,11.92,14.83,14.75,13.15,16.26,11.3,9.7,13.3,31,77.8,6030,12.8,1464,2.992,18,12.91,7.652,20.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,7.884,5.15,11.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.65,37.9,41.18,1637,6.715,5.523,7.906,300,3.1,2.027,4.172,82.45,1213:1,502,88.68,4.169,2.22,6.117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49411,4.627e+04,5.256e+04,NaN,NaN,NaN,76250,4.591e+04,1.066e+05,45208,4.209e+04,4.832e+04,NaN,NaN,NaN,48538,4.682e+04,5.026e+04,49.86,NaN,39.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,15.62,10.75,21.94,15.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,12.4,8.302,17.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,24,3200,13.75,35.83,13678,76.21,75.31,77.11,1807,10.47,9.073,11.86,75.11,13480,73.62,76.59,46091,20.12,19.65,595,1.291,147,0.3189,577,1.252,19,0.04122,784,1.701,43456,94.28,244,0.551,0.2736,0.8285,49.19,38540,78.74
4,36005,New York,Bronx,80.89,80.7,81.07,NaN,NaN,NaN,91.72,89.37,94.06,78.99,78.64,79.35,83.41,83.08,83.73,79.11,78.6,79.62,15102,345.6,340,351.1,NaN,NaN,NaN,163.7,145.3,182.1,419.6,408.6,430.6,285.4,278.4,292.5,393.3,374.9,411.7,611,42.51,39.14,45.88,NaN,NaN,NaN,39.12,23.89,60.41,63.87,56.13,71.62,29.01,25.46,32.55,55.54,40.95,73.63,728,4.889,4.534,5.244,NaN,NaN,NaN,5.249,3.363,7.811,7.337,6.52,8.153,3.073,2.715,3.431,5.131,3.796,6.783,15.66,14.38,16.89,14.81,13.59,15.92,12.7,11.4,14.2,27625,2357,251180,17.5,12.74,0.0009199,1165,26.96,25.41,28.51,NaN,NaN,NaN,NaN,NaN,NaN,28.33,25.43,31.24,24.41,22.45,26.38,42.46,36.09,48.82,359,3.558,3.19,3.926,NaN,NaN,NaN,NaN,NaN,NaN,2.996,2.412,3.679,3.26,2.787,3.732,7.159,5.591,9.03,42.45,41.31,43.46,97537,11.28,10.33,12.23,7673,2.161,1.684,2.638,124.2,805:1,14557,67.17,9.396,8.339,10.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41470,4.017e+04,4.277e+04,30010,2.251e+04,3.751e+04,55493,5.147e+04,5.952e+04,41378,4.038e+04,4.238e+04,34614,3.361e+04,3.562e+04,63960,6.189e+04,6.603e+04,85.57,45.5,37.47,6.304,5.814,6.793,NaN,NaN,NaN,NaN,NaN,NaN,11.26,10.07,12.45,4.613,4.052,5.175,2.218,1.39,3.359,396,5.431,4.889,5.974,5.475,NaN,NaN,NaN,5.639,3.223,9.157,4.815,3.888,5.742,4.647,3.969,5.326,10.84,8.454,13.7,312,4.314,3.835,4.792,NaN,NaN,NaN,NaN,NaN,NaN,7.699,6.531,8.866,2.938,2.41,3.466,2.757,1.66,4.305,231,376,112700,5.386,3716,99212,19.69,19.22,20.17,149739,31.04,30.39,31.7,75.73,381549,75.08,76.38,1418207,24.58,13.31,414684,29.24,41319,2.913,64686,4.561,5975,0.4213,799580,56.38,127783,9.01,206972,15.56,15.19,15.93,52.79,39,0.002816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [ ]:
#Remove columns
to_remove=df12.iloc[:,np.r_[1:3,4:84,85:90,91,93:144,146:159,160:177,178:258,259,261,263,265,267,269:276]]
df12c=df12.drop(columns=to_remove)

#Remove rows
df12c=df12c.drop([0,1])

#Rename columns
new_col12={'Unnamed: 0': 'fips',
          'Life expectancy':'life_expectancy',
          'Diabetes prevalence':'%diabetes',
          'Unnamed: 90':'%food_insecure',
          'Unnamed: 92':'%limited_access',
          'High school graduation': 'graduation_cohort',
          'Unnamed: 145': 'graduation_rate',
          'Median household income':'household_income',
          'Children eligible for free or reduced price lunch':'%lunch_aid',
          'Unnamed: 258':'%african_american',
          'Unnamed: 260':'%american_indian',
          'Unnamed: 262':'%asian',
          'Unnamed: 264':'%pacific_islander',
          'Unnamed: 266':'%hispanic',
          'Unnamed: 268':'%white'
    
}
df12c=df12c.rename(columns=new_col12)
df12c

,fips,life_expectancy,%diabetes,%food_insecure,%limited_access,graduation_cohort,graduation_rate,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
2,36001,79.95,9.7,10.2,4.78,3009,84.92,69408,40.62,12.78,0.3044,6.836,0.06612,6.253,71.57
3,36003,77.91,11.3,12.8,2.992,502,88.68,49411,49.86,1.291,0.3189,1.252,0.04122,1.701,94.28
4,36005,80.89,12.7,17.5,0.0009199,14557,67.17,41470,85.57,29.24,2.913,4.561,0.4213,56.38,9.01
5,36007,78.62,10.6,12.7,3.241,2157,83.52,52179,52.31,5.579,0.2725,4.422,0.06772,4.45,82.7
6,36009,77.58,14.3,12.8,2.584,1040,85.92,50783,49.1,1.324,3.602,0.8474,0.03941,2.148,90.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,36115,78.73,13.5,10.5,4.286,691,79.88,56897,42.57,3.042,0.3415,0.5784,0.04085,2.943,92.02
60,36117,79.03,13.2,10.1,3.489,1162,87.77,61989,46.75,2.864,0.4315,0.7162,0.04782,4.693,89.51
61,36119,83.65,7.9,7.8,1.379,11145,89.87,101741,33.25,13.82,0.9687,6.464,0.1409,25.55,52.62
62,36121,79.18,11.9,10.1,6.067,340,92.5,58214,42.04,5.073,0.4616,0.5243,0.03512,3.314,89.85
63,36123,77.65,14.1,9.4,0.5,214,79.65,60612,55.72,0.859,0.3251,0.7948,0.02007,2.28,94.8

### Merge 4 sheets

In [ ]:
#Merge first 2
merged_df5=pd.merge(df9c,df10c,on='fips',how='outer')

#Merge second 2
merged_df6=pd.merge(df11c,df12c,on='fips',how='outer')

#Merge all together
rank2021=pd.merge(merged_df5,merged_df6,on='fips',how='outer')


#Keep only counties in NYC
#county_nyc=['New York','Kings','Bronx','Richmond','Queens']
#rank2021=rank2021[rank2021['county_name'].isin(county_nyc)]
rank2021=rank2021.reset_index().drop(columns=['index','health_outcomes_z','health_factors_z','lenght_life_z','quality_life_z'])
show = rank2021[rank2021.isna().any(axis=1)]
show

,fips,state,county_name,health_outcomes_r,health_factors_r,length_life_r,quality_life_r,yppl,%poor_fair_health,%adult_obesity,food_environment_index,%some_college,life_expectancy,%diabetes,%food_insecure,%limited_access,graduation_cohort,graduation_rate,household_income,%lunch_aid,%african_american,%american_indian,%asian,%pacific_islander,%hispanic,%white
20,36041,New York,Hamilton,23,33,30,14,NaN,16.71,29.7,7.4,59.32,78.85,12.7,11.8,12.09,NaN,NaN,60148,44.79,0.9964,0.3397,0.7699,0.09058,1.97,94.5

In [ ]:
#change data types
floats=['%poor_fair_health','%adult_obesity','food_environment_index','graduation_rate','%some_college','life_expectancy','%diabetes','%food_insecure',
        '%limited_access','%lunch_aid','%african_american','%american_indian','%asian','%pacific_islander','%hispanic','%white']

ints=['fips','health_outcomes_r','health_factors_r','length_life_r','quality_life_r','household_income']

rank2021[floats]=rank2021[floats].astype(float)
rank2021[ints]=rank2021[ints].astype(int)

#Save and export
pd.set_option("display.precision", 4)
rank2021.to_csv('rank2021.csv',encoding='utf-8',index=False)

In [ ]:
rank2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fips                    62 non-null     int64
 1   state                   62 non-null     object
 2   county_name             62 non-null     object
 3   health_outcomes_r       62 non-null     int64
 4   health_factors_r        62 non-null     int64
 5   length_life_r           62 non-null     int64
 6   quality_life_r          62 non-null     int64
 7   yppl                    61 non-null     object
 8   %poor_fair_health       62 non-null     float64
 9   %adult_obesity          62 non-null     float64
 10  food_environment_index  62 non-null     float64
 11  %some_college           62 non-null     float64
 12  life_expectancy         62 non-null     float64
 13  %diabetes               62 non-null     float64
 14  %food_insecure          62 non-null     float64
 15  %limited_access         62 non-null     float64
 16  graduation_cohort       61 non-null     object
 17  graduation_rate         61 non-null     float64
 18  household_income        62 non-null     int64
 19  %lunch_aid              62 non-null     float64
 20  %african_american       62 non-null     float64
 21  %american_indian        62 non-null     float64
 22  %asian                  62 non-null     float64
 23  %pacific_islander       62 non-null     float64
 24  %hispanic               62 non-null     float64
 25  %white                  62 non-null     float64
dtypes: float64(16), int64(6), object(4)
memory usage: 12.7+ KB